//
// ColorsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Envelope returned by the colour reference endpoint. */
public struct ColorsResponse: Codable, JSONEncodable, Hashable {

    public var colors: [VintedColor]

    public init(colors: [VintedColor]) {
        self.colors = colors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case colors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(colors, forKey: .colors)
    }
}

