//
// FilterRuleValidateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Validation result for a Twitter search query. */
public struct FilterRuleValidateResponse: Codable, JSONEncodable, Hashable {

    public var valid: Bool
    public var query: String
    public var error: String?

    public init(valid: Bool, query: String, error: String? = nil) {
        self.valid = valid
        self.query = query
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case valid
        case query
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(valid, forKey: .valid)
        try container.encode(query, forKey: .query)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

