//
// FilterRuleResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Filter rule response.  Per-poll billing — see &#x60;&#x60;GET /v1/twitter/filter-rules/pricing&#x60;&#x60; for the rates that apply globally to every rule. */
public struct FilterRuleResponse: Codable, JSONEncodable, Hashable {

    public var id: String
    public var tag: String
    public var query: String
    public var intervalSeconds: Double
    public var maxResultsPerPoll: Int
    public var status: String
    public var statusReason: String?
    public var webhookUrl: String?
    public var webhookSecretSet: Bool
    public var totalCreditsBurned: Double
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: String, tag: String, query: String, intervalSeconds: Double, maxResultsPerPoll: Int, status: String, statusReason: String?, webhookUrl: String?, webhookSecretSet: Bool, totalCreditsBurned: Double, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.tag = tag
        self.query = query
        self.intervalSeconds = intervalSeconds
        self.maxResultsPerPoll = maxResultsPerPoll
        self.status = status
        self.statusReason = statusReason
        self.webhookUrl = webhookUrl
        self.webhookSecretSet = webhookSecretSet
        self.totalCreditsBurned = totalCreditsBurned
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tag
        case query
        case intervalSeconds = "interval_seconds"
        case maxResultsPerPoll = "max_results_per_poll"
        case status
        case statusReason = "status_reason"
        case webhookUrl = "webhook_url"
        case webhookSecretSet = "webhook_secret_set"
        case totalCreditsBurned = "total_credits_burned"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tag, forKey: .tag)
        try container.encode(query, forKey: .query)
        try container.encode(intervalSeconds, forKey: .intervalSeconds)
        try container.encode(maxResultsPerPoll, forKey: .maxResultsPerPoll)
        try container.encode(status, forKey: .status)
        try container.encode(statusReason, forKey: .statusReason)
        try container.encode(webhookUrl, forKey: .webhookUrl)
        try container.encode(webhookSecretSet, forKey: .webhookSecretSet)
        try container.encode(totalCreditsBurned, forKey: .totalCreditsBurned)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

