//
// PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Per-poll rates for filter rules (no tiers — usage-based). */
public struct PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse: Codable, JSONEncodable, Hashable {

    public var creditsPerEmptyCall: Double
    public var creditsPerTweetReturned: Double

    public init(creditsPerEmptyCall: Double, creditsPerTweetReturned: Double) {
        self.creditsPerEmptyCall = creditsPerEmptyCall
        self.creditsPerTweetReturned = creditsPerTweetReturned
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case creditsPerEmptyCall = "credits_per_empty_call"
        case creditsPerTweetReturned = "credits_per_tweet_returned"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(creditsPerEmptyCall, forKey: .creditsPerEmptyCall)
        try container.encode(creditsPerTweetReturned, forKey: .creditsPerTweetReturned)
    }
}

