//
// StreamMonitorListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Paginated list of stream monitors. */
public struct StreamMonitorListResponse: Codable, JSONEncodable, Hashable {

    public var monitors: [StreamMonitorResponse]
    public var total: Int
    public var page: Int
    public var pageSize: Int

    public init(monitors: [StreamMonitorResponse], total: Int, page: Int, pageSize: Int) {
        self.monitors = monitors
        self.total = total
        self.page = page
        self.pageSize = pageSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case monitors
        case total
        case page
        case pageSize = "page_size"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(monitors, forKey: .monitors)
        try container.encode(total, forKey: .total)
        try container.encode(page, forKey: .page)
        try container.encode(pageSize, forKey: .pageSize)
    }
}

