//
// StreamMonitorUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Partial update stream monitor request. */
public struct StreamMonitorUpdate: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: 100, pattern: nil)
    static let usernamesRule = ArrayRule(minItems: 1, maxItems: 100, uniqueItems: false)
    static let statusRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^(active|paused)$/")
    public var name: String?
    public var usernames: [String]?
    public var status: String?
    public var webhookUrl: String?
    public var webhookSecret: String?
    public var filterTypes: [String]?

    public init(name: String? = nil, usernames: [String]? = nil, status: String? = nil, webhookUrl: String? = nil, webhookSecret: String? = nil, filterTypes: [String]? = nil) {
        self.name = name
        self.usernames = usernames
        self.status = status
        self.webhookUrl = webhookUrl
        self.webhookSecret = webhookSecret
        self.filterTypes = filterTypes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case usernames
        case status
        case webhookUrl = "webhook_url"
        case webhookSecret = "webhook_secret"
        case filterTypes = "filter_types"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(usernames, forKey: .usernames)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(webhookUrl, forKey: .webhookUrl)
        try container.encodeIfPresent(webhookSecret, forKey: .webhookSecret)
        try container.encodeIfPresent(filterTypes, forKey: .filterTypes)
    }
}

