//
// SubscriptionInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Active subscription details (null when PAYG-only). */
public struct SubscriptionInfo: Codable, JSONEncodable, Hashable {

    public var planCode: String
    public var planTitle: String
    public var billingCadence: String
    public var status: String
    public var currentPeriodStart: Date?
    public var currentPeriodEnd: Date?
    public var cancelAtPeriodEnd: Bool? = false
    public var cancelEffectiveAt: Date?
    public var monthlyCredits: Int? = 0
    public var pendingPlanCode: String?
    public var pendingPlanTitle: String?
    public var pendingChangeEffectiveAt: Date?

    public init(planCode: String, planTitle: String, billingCadence: String, status: String, currentPeriodStart: Date? = nil, currentPeriodEnd: Date? = nil, cancelAtPeriodEnd: Bool? = false, cancelEffectiveAt: Date? = nil, monthlyCredits: Int? = 0, pendingPlanCode: String? = nil, pendingPlanTitle: String? = nil, pendingChangeEffectiveAt: Date? = nil) {
        self.planCode = planCode
        self.planTitle = planTitle
        self.billingCadence = billingCadence
        self.status = status
        self.currentPeriodStart = currentPeriodStart
        self.currentPeriodEnd = currentPeriodEnd
        self.cancelAtPeriodEnd = cancelAtPeriodEnd
        self.cancelEffectiveAt = cancelEffectiveAt
        self.monthlyCredits = monthlyCredits
        self.pendingPlanCode = pendingPlanCode
        self.pendingPlanTitle = pendingPlanTitle
        self.pendingChangeEffectiveAt = pendingChangeEffectiveAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case planCode = "plan_code"
        case planTitle = "plan_title"
        case billingCadence = "billing_cadence"
        case status
        case currentPeriodStart = "current_period_start"
        case currentPeriodEnd = "current_period_end"
        case cancelAtPeriodEnd = "cancel_at_period_end"
        case cancelEffectiveAt = "cancel_effective_at"
        case monthlyCredits = "monthly_credits"
        case pendingPlanCode = "pending_plan_code"
        case pendingPlanTitle = "pending_plan_title"
        case pendingChangeEffectiveAt = "pending_change_effective_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(planCode, forKey: .planCode)
        try container.encode(planTitle, forKey: .planTitle)
        try container.encode(billingCadence, forKey: .billingCadence)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(currentPeriodStart, forKey: .currentPeriodStart)
        try container.encodeIfPresent(currentPeriodEnd, forKey: .currentPeriodEnd)
        try container.encodeIfPresent(cancelAtPeriodEnd, forKey: .cancelAtPeriodEnd)
        try container.encodeIfPresent(cancelEffectiveAt, forKey: .cancelEffectiveAt)
        try container.encodeIfPresent(monthlyCredits, forKey: .monthlyCredits)
        try container.encodeIfPresent(pendingPlanCode, forKey: .pendingPlanCode)
        try container.encodeIfPresent(pendingPlanTitle, forKey: .pendingPlanTitle)
        try container.encodeIfPresent(pendingChangeEffectiveAt, forKey: .pendingChangeEffectiveAt)
    }
}

