//
// TweetDeliveryLogResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Tweet delivery log entry. */
public struct TweetDeliveryLogResponse: Codable, JSONEncodable, Hashable {

    public var id: String
    public var monitorId: String
    public var monitorName: String
    public var tweetId: String
    public var authorUsername: String
    public var tweetTextPreview: String?
    public var tweetUrl: String
    public var tweetPublishedAt: Date
    public var detectedAt: Date
    public var latencyMs: Int
    public var latencyBadge: String
    public var deliveryStatus: String
    public var webhookStatusCode: Int?
    public var webhookAttempts: Int

    public init(id: String, monitorId: String, monitorName: String, tweetId: String, authorUsername: String, tweetTextPreview: String?, tweetUrl: String, tweetPublishedAt: Date, detectedAt: Date, latencyMs: Int, latencyBadge: String, deliveryStatus: String, webhookStatusCode: Int?, webhookAttempts: Int) {
        self.id = id
        self.monitorId = monitorId
        self.monitorName = monitorName
        self.tweetId = tweetId
        self.authorUsername = authorUsername
        self.tweetTextPreview = tweetTextPreview
        self.tweetUrl = tweetUrl
        self.tweetPublishedAt = tweetPublishedAt
        self.detectedAt = detectedAt
        self.latencyMs = latencyMs
        self.latencyBadge = latencyBadge
        self.deliveryStatus = deliveryStatus
        self.webhookStatusCode = webhookStatusCode
        self.webhookAttempts = webhookAttempts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case monitorId = "monitor_id"
        case monitorName = "monitor_name"
        case tweetId = "tweet_id"
        case authorUsername = "author_username"
        case tweetTextPreview = "tweet_text_preview"
        case tweetUrl = "tweet_url"
        case tweetPublishedAt = "tweet_published_at"
        case detectedAt = "detected_at"
        case latencyMs = "latency_ms"
        case latencyBadge = "latency_badge"
        case deliveryStatus = "delivery_status"
        case webhookStatusCode = "webhook_status_code"
        case webhookAttempts = "webhook_attempts"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(monitorId, forKey: .monitorId)
        try container.encode(monitorName, forKey: .monitorName)
        try container.encode(tweetId, forKey: .tweetId)
        try container.encode(authorUsername, forKey: .authorUsername)
        try container.encode(tweetTextPreview, forKey: .tweetTextPreview)
        try container.encode(tweetUrl, forKey: .tweetUrl)
        try container.encode(tweetPublishedAt, forKey: .tweetPublishedAt)
        try container.encode(detectedAt, forKey: .detectedAt)
        try container.encode(latencyMs, forKey: .latencyMs)
        try container.encode(latencyBadge, forKey: .latencyBadge)
        try container.encode(deliveryStatus, forKey: .deliveryStatus)
        try container.encode(webhookStatusCode, forKey: .webhookStatusCode)
        try container.encode(webhookAttempts, forKey: .webhookAttempts)
    }
}

