//
// UserItemsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Envelope returned by a seller&#39;s wardrobe listing. */
public struct UserItemsResponse: Codable, JSONEncodable, Hashable {

    public var items: [VintedItemSummary]
    public var pagination: VintedPagination
    public var market: String

    public init(items: [VintedItemSummary], pagination: VintedPagination, market: String) {
        self.items = items
        self.pagination = pagination
        self.market = market
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case pagination
        case market
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encode(pagination, forKey: .pagination)
        try container.encode(market, forKey: .market)
    }
}

