//
// VintedMobileReadRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Parameters are validated against the discoverable operation catalog. */
public struct VintedMobileReadRequest: Codable, JSONEncodable, Hashable {

    /** Vinted market code; uk aliases gb */
    public var market: String? = "fr"
    /** Operation-specific parameters. GET /v1/vinted/mobile/operations lists types, required fields and examples. */
    public var parameters: [String: AnyCodable]?

    public init(market: String? = "fr", parameters: [String: AnyCodable]? = nil) {
        self.market = market
        self.parameters = parameters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case market
        case parameters
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(market, forKey: .market)
        try container.encodeIfPresent(parameters, forKey: .parameters)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        market = try container.decodeIfPresent(String.self, forKey: .market)
        parameters = try container.decodeIfPresent([String: AnyCodable].self, forKey: .parameters)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("market")
        nonAdditionalPropertyKeys.insert("parameters")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

