//
// VintedUserProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A seller&#39;s public profile. */
public struct VintedUserProfile: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var login: String
    public var photoUrl: String?
    public var business: Bool? = false
    public var countryCode: String?
    public var city: String?
    public var feedbackCount: Int? = 0
    public var feedbackReputation: Double? = 0.0
    public var positiveFeedbackCount: Int? = 0
    public var neutralFeedbackCount: Int? = 0
    public var negativeFeedbackCount: Int? = 0
    public var itemCount: Int? = 0
    public var totalItemsCount: Int? = 0
    public var followersCount: Int? = 0
    public var followingCount: Int? = 0
    public var isOnline: Bool? = false
    public var isOnHoliday: Bool? = false
    public var lastLogedOnTs: String?
    public var profileUrl: String?
    public var locale: String?

    public init(id: Int, login: String, photoUrl: String? = nil, business: Bool? = false, countryCode: String? = nil, city: String? = nil, feedbackCount: Int? = 0, feedbackReputation: Double? = 0.0, positiveFeedbackCount: Int? = 0, neutralFeedbackCount: Int? = 0, negativeFeedbackCount: Int? = 0, itemCount: Int? = 0, totalItemsCount: Int? = 0, followersCount: Int? = 0, followingCount: Int? = 0, isOnline: Bool? = false, isOnHoliday: Bool? = false, lastLogedOnTs: String? = nil, profileUrl: String? = nil, locale: String? = nil) {
        self.id = id
        self.login = login
        self.photoUrl = photoUrl
        self.business = business
        self.countryCode = countryCode
        self.city = city
        self.feedbackCount = feedbackCount
        self.feedbackReputation = feedbackReputation
        self.positiveFeedbackCount = positiveFeedbackCount
        self.neutralFeedbackCount = neutralFeedbackCount
        self.negativeFeedbackCount = negativeFeedbackCount
        self.itemCount = itemCount
        self.totalItemsCount = totalItemsCount
        self.followersCount = followersCount
        self.followingCount = followingCount
        self.isOnline = isOnline
        self.isOnHoliday = isOnHoliday
        self.lastLogedOnTs = lastLogedOnTs
        self.profileUrl = profileUrl
        self.locale = locale
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case login
        case photoUrl = "photo_url"
        case business
        case countryCode = "country_code"
        case city
        case feedbackCount = "feedback_count"
        case feedbackReputation = "feedback_reputation"
        case positiveFeedbackCount = "positive_feedback_count"
        case neutralFeedbackCount = "neutral_feedback_count"
        case negativeFeedbackCount = "negative_feedback_count"
        case itemCount = "item_count"
        case totalItemsCount = "total_items_count"
        case followersCount = "followers_count"
        case followingCount = "following_count"
        case isOnline = "is_online"
        case isOnHoliday = "is_on_holiday"
        case lastLogedOnTs = "last_loged_on_ts"
        case profileUrl = "profile_url"
        case locale
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(login, forKey: .login)
        try container.encodeIfPresent(photoUrl, forKey: .photoUrl)
        try container.encodeIfPresent(business, forKey: .business)
        try container.encodeIfPresent(countryCode, forKey: .countryCode)
        try container.encodeIfPresent(city, forKey: .city)
        try container.encodeIfPresent(feedbackCount, forKey: .feedbackCount)
        try container.encodeIfPresent(feedbackReputation, forKey: .feedbackReputation)
        try container.encodeIfPresent(positiveFeedbackCount, forKey: .positiveFeedbackCount)
        try container.encodeIfPresent(neutralFeedbackCount, forKey: .neutralFeedbackCount)
        try container.encodeIfPresent(negativeFeedbackCount, forKey: .negativeFeedbackCount)
        try container.encodeIfPresent(itemCount, forKey: .itemCount)
        try container.encodeIfPresent(totalItemsCount, forKey: .totalItemsCount)
        try container.encodeIfPresent(followersCount, forKey: .followersCount)
        try container.encodeIfPresent(followingCount, forKey: .followingCount)
        try container.encodeIfPresent(isOnline, forKey: .isOnline)
        try container.encodeIfPresent(isOnHoliday, forKey: .isOnHoliday)
        try container.encodeIfPresent(lastLogedOnTs, forKey: .lastLogedOnTs)
        try container.encodeIfPresent(profileUrl, forKey: .profileUrl)
        try container.encodeIfPresent(locale, forKey: .locale)
    }
}

