//
// VintedUserSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Seller as nested in an item response. */
public struct VintedUserSummary: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var login: String
    public var photoUrl: String?
    public var business: Bool? = false

    public init(id: Int, login: String, photoUrl: String? = nil, business: Bool? = false) {
        self.id = id
        self.login = login
        self.photoUrl = photoUrl
        self.business = business
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case login
        case photoUrl = "photo_url"
        case business
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(login, forKey: .login)
        try container.encodeIfPresent(photoUrl, forKey: .photoUrl)
        try container.encodeIfPresent(business, forKey: .business)
    }
}

