//
// VintedPhoto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One item photo. */
public struct VintedPhoto: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var url: String
    public var dominantColor: String?
    public var isMain: Bool? = false
    public var width: Int?
    public var height: Int?
    public var fullSizeUrl: String?

    public init(id: Int, url: String, dominantColor: String? = nil, isMain: Bool? = false, width: Int? = nil, height: Int? = nil, fullSizeUrl: String? = nil) {
        self.id = id
        self.url = url
        self.dominantColor = dominantColor
        self.isMain = isMain
        self.width = width
        self.height = height
        self.fullSizeUrl = fullSizeUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case url
        case dominantColor = "dominant_color"
        case isMain = "is_main"
        case width
        case height
        case fullSizeUrl = "full_size_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(dominantColor, forKey: .dominantColor)
        try container.encodeIfPresent(isMain, forKey: .isMain)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(fullSizeUrl, forKey: .fullSizeUrl)
    }
}

