//
// VintedPrice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Money value. The amount is a decimal string, never a float. */
public struct VintedPrice: Codable, JSONEncodable, Hashable {

    public var amount: String
    public var currencyCode: String

    public init(amount: String, currencyCode: String) {
        self.amount = amount
        self.currencyCode = currencyCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case currencyCode = "currency_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(currencyCode, forKey: .currencyCode)
    }
}

