//
// AirbnbAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AirbnbAPI {

    /**
     Airbnb scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func airbnbAirbnbScraperHealthCheck(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return airbnbAirbnbScraperHealthCheckWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Airbnb scraper health check
     - GET /v1/airbnb/health
     - Check health of the Airbnb scraper service (accepts HEAD).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func airbnbAirbnbScraperHealthCheckWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/airbnb/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Airbnb scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func airbnbAirbnbScraperHealthCheckHead(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return airbnbAirbnbScraperHealthCheckHeadWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Airbnb scraper health check
     - HEAD /v1/airbnb/health
     - Check health of the Airbnb scraper service (accepts HEAD).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func airbnbAirbnbScraperHealthCheckHeadWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/airbnb/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get availability calendar
     
     - parameter roomId: (path)  
     - parameter month: (query) Start month (1-12) (optional, default to 1)
     - parameter year: (query) Start year (optional, default to 2026)
     - parameter months: (query) Number of months (max 12) (optional, default to 12)
     - parameter currency: (query)  (optional)
     - parameter locale: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func airbnbGetAvailabilityCalendar(roomId: String, month: Int? = nil, year: Int? = nil, months: Int? = nil, currency: String? = nil, locale: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return airbnbGetAvailabilityCalendarWithRequestBuilder(roomId: roomId, month: month, year: year, months: months, currency: currency, locale: locale).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get availability calendar
     - GET /v1/airbnb/listings/{room_id}/calendar
     - Day-by-day availability for up to 12 months: bookable, check-in/out windows and min/max nights per date.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter roomId: (path)  
     - parameter month: (query) Start month (1-12) (optional, default to 1)
     - parameter year: (query) Start year (optional, default to 2026)
     - parameter months: (query) Number of months (max 12) (optional, default to 12)
     - parameter currency: (query)  (optional)
     - parameter locale: (query)  (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func airbnbGetAvailabilityCalendarWithRequestBuilder(roomId: String, month: Int? = nil, year: Int? = nil, months: Int? = nil, currency: String? = nil, locale: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/airbnb/listings/{room_id}/calendar"
        let roomIdPreEscape = "\(APIHelper.mapValueToPathItem(roomId))"
        let roomIdPostEscape = roomIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{room_id}", with: roomIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "month": (wrappedValue: month?.encodeToJSON(), isExplode: true),
            "year": (wrappedValue: year?.encodeToJSON(), isExplode: true),
            "months": (wrappedValue: months?.encodeToJSON(), isExplode: true),
            "currency": (wrappedValue: currency?.encodeToJSON(), isExplode: true),
            "locale": (wrappedValue: locale?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get experience detail
     
     - parameter experienceId: (path)  
     - parameter adults: (query)  (optional, default to 1)
     - parameter children: (query)  (optional, default to 0)
     - parameter infants: (query)  (optional, default to 0)
     - parameter currency: (query)  (optional)
     - parameter locale: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func airbnbGetExperienceDetail(experienceId: String, adults: Int? = nil, children: Int? = nil, infants: Int? = nil, currency: String? = nil, locale: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return airbnbGetExperienceDetailWithRequestBuilder(experienceId: experienceId, adults: adults, children: children, infants: infants, currency: currency, locale: locale).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get experience detail
     - GET /v1/airbnb/experiences/{experience_id}
     - Full detail for one experience: description, rating, host, location and photos.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter experienceId: (path)  
     - parameter adults: (query)  (optional, default to 1)
     - parameter children: (query)  (optional, default to 0)
     - parameter infants: (query)  (optional, default to 0)
     - parameter currency: (query)  (optional)
     - parameter locale: (query)  (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func airbnbGetExperienceDetailWithRequestBuilder(experienceId: String, adults: Int? = nil, children: Int? = nil, infants: Int? = nil, currency: String? = nil, locale: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/airbnb/experiences/{experience_id}"
        let experienceIdPreEscape = "\(APIHelper.mapValueToPathItem(experienceId))"
        let experienceIdPostEscape = experienceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{experience_id}", with: experienceIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "adults": (wrappedValue: adults?.encodeToJSON(), isExplode: true),
            "children": (wrappedValue: children?.encodeToJSON(), isExplode: true),
            "infants": (wrappedValue: infants?.encodeToJSON(), isExplode: true),
            "currency": (wrappedValue: currency?.encodeToJSON(), isExplode: true),
            "locale": (wrappedValue: locale?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get listing detail
     
     - parameter roomId: (path)  
     - parameter adults: (query)  (optional, default to 1)
     - parameter currency: (query)  (optional)
     - parameter locale: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func airbnbGetListingDetail(roomId: String, adults: Int? = nil, currency: String? = nil, locale: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return airbnbGetListingDetailWithRequestBuilder(roomId: roomId, adults: adults, currency: currency, locale: locale).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get listing detail
     - GET /v1/airbnb/listings/{room_id}
     - Full detail for one listing: amenities, house rules, host, ratings, coordinates and photos.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter roomId: (path)  
     - parameter adults: (query)  (optional, default to 1)
     - parameter currency: (query)  (optional)
     - parameter locale: (query)  (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func airbnbGetListingDetailWithRequestBuilder(roomId: String, adults: Int? = nil, currency: String? = nil, locale: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/airbnb/listings/{room_id}"
        let roomIdPreEscape = "\(APIHelper.mapValueToPathItem(roomId))"
        let roomIdPostEscape = roomIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{room_id}", with: roomIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "adults": (wrappedValue: adults?.encodeToJSON(), isExplode: true),
            "currency": (wrappedValue: currency?.encodeToJSON(), isExplode: true),
            "locale": (wrappedValue: locale?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get listing reviews
     
     - parameter roomId: (path)  
     - parameter limit: (query)  (optional, default to 24)
     - parameter offset: (query)  (optional, default to 0)
     - parameter sort: (query) MOST_RECENT | RATING_DESC | RATING_ASC (optional, default to "MOST_RECENT")
     - parameter currency: (query)  (optional)
     - parameter locale: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func airbnbGetListingReviews(roomId: String, limit: Int? = nil, offset: Int? = nil, sort: String? = nil, currency: String? = nil, locale: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return airbnbGetListingReviewsWithRequestBuilder(roomId: roomId, limit: limit, offset: offset, sort: sort, currency: currency, locale: locale).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get listing reviews
     - GET /v1/airbnb/listings/{room_id}/reviews
     - Paginated guest reviews with reviewer, rating, date, text and host response.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter roomId: (path)  
     - parameter limit: (query)  (optional, default to 24)
     - parameter offset: (query)  (optional, default to 0)
     - parameter sort: (query) MOST_RECENT | RATING_DESC | RATING_ASC (optional, default to "MOST_RECENT")
     - parameter currency: (query)  (optional)
     - parameter locale: (query)  (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func airbnbGetListingReviewsWithRequestBuilder(roomId: String, limit: Int? = nil, offset: Int? = nil, sort: String? = nil, currency: String? = nil, locale: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/airbnb/listings/{room_id}/reviews"
        let roomIdPreEscape = "\(APIHelper.mapValueToPathItem(roomId))"
        let roomIdPostEscape = roomIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{room_id}", with: roomIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
            "currency": (wrappedValue: currency?.encodeToJSON(), isExplode: true),
            "locale": (wrappedValue: locale?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search experiences
     
     - parameter location: (query) Free-text place, e.g. &#39;Rome, Italy&#39; 
     - parameter cursor: (query) next_page_cursor from a prior response (optional)
     - parameter currency: (query)  (optional)
     - parameter locale: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func airbnbSearchExperiences(location: String, cursor: String? = nil, currency: String? = nil, locale: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return airbnbSearchExperiencesWithRequestBuilder(location: location, cursor: cursor, currency: currency, locale: locale).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search experiences
     - GET /v1/airbnb/experiences
     - Search Airbnb Experiences by location.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter location: (query) Free-text place, e.g. &#39;Rome, Italy&#39; 
     - parameter cursor: (query) next_page_cursor from a prior response (optional)
     - parameter currency: (query)  (optional)
     - parameter locale: (query)  (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func airbnbSearchExperiencesWithRequestBuilder(location: String, cursor: String? = nil, currency: String? = nil, locale: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/airbnb/experiences"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "location": (wrappedValue: location.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
            "currency": (wrappedValue: currency?.encodeToJSON(), isExplode: true),
            "locale": (wrappedValue: locale?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search stays
     
     - parameter location: (query) Free-text place, e.g. &#39;Paris, France&#39; (optional)
     - parameter neLat: (query) Map bounding-box NE latitude (optional)
     - parameter neLng: (query) Map bounding-box NE longitude (optional)
     - parameter swLat: (query) Map bounding-box SW latitude (optional)
     - parameter swLng: (query) Map bounding-box SW longitude (optional)
     - parameter checkIn: (query) Check-in date YYYY-MM-DD (optional)
     - parameter checkOut: (query) Check-out date YYYY-MM-DD (optional)
     - parameter adults: (query)  (optional, default to 1)
     - parameter children: (query)  (optional, default to 0)
     - parameter infants: (query)  (optional, default to 0)
     - parameter pets: (query)  (optional, default to 0)
     - parameter priceMin: (query)  (optional)
     - parameter priceMax: (query)  (optional)
     - parameter minBedrooms: (query)  (optional)
     - parameter minBeds: (query)  (optional)
     - parameter minBathrooms: (query)  (optional)
     - parameter roomType: (query) e.g. &#39;Entire home/apt&#39;, &#39;Private room&#39; (optional)
     - parameter cursor: (query) next_page_cursor from a prior response (optional)
     - parameter limit: (query)  (optional, default to 18)
     - parameter currency: (query) ISO currency, e.g. USD, EUR (optional)
     - parameter locale: (query) Locale, e.g. en, fr (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func airbnbSearchStays(location: String? = nil, neLat: Double? = nil, neLng: Double? = nil, swLat: Double? = nil, swLng: Double? = nil, checkIn: String? = nil, checkOut: String? = nil, adults: Int? = nil, children: Int? = nil, infants: Int? = nil, pets: Int? = nil, priceMin: Int? = nil, priceMax: Int? = nil, minBedrooms: Int? = nil, minBeds: Int? = nil, minBathrooms: Int? = nil, roomType: String? = nil, cursor: String? = nil, limit: Int? = nil, currency: String? = nil, locale: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return airbnbSearchStaysWithRequestBuilder(location: location, neLat: neLat, neLng: neLng, swLat: swLat, swLng: swLng, checkIn: checkIn, checkOut: checkOut, adults: adults, children: children, infants: infants, pets: pets, priceMin: priceMin, priceMax: priceMax, minBedrooms: minBedrooms, minBeds: minBeds, minBathrooms: minBathrooms, roomType: roomType, cursor: cursor, limit: limit, currency: currency, locale: locale).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search stays
     - GET /v1/airbnb/search
     - Search Airbnb stays by place name and/or map bounding box, with dates, guests, price and property filters. Paginate with the `cursor`.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter location: (query) Free-text place, e.g. &#39;Paris, France&#39; (optional)
     - parameter neLat: (query) Map bounding-box NE latitude (optional)
     - parameter neLng: (query) Map bounding-box NE longitude (optional)
     - parameter swLat: (query) Map bounding-box SW latitude (optional)
     - parameter swLng: (query) Map bounding-box SW longitude (optional)
     - parameter checkIn: (query) Check-in date YYYY-MM-DD (optional)
     - parameter checkOut: (query) Check-out date YYYY-MM-DD (optional)
     - parameter adults: (query)  (optional, default to 1)
     - parameter children: (query)  (optional, default to 0)
     - parameter infants: (query)  (optional, default to 0)
     - parameter pets: (query)  (optional, default to 0)
     - parameter priceMin: (query)  (optional)
     - parameter priceMax: (query)  (optional)
     - parameter minBedrooms: (query)  (optional)
     - parameter minBeds: (query)  (optional)
     - parameter minBathrooms: (query)  (optional)
     - parameter roomType: (query) e.g. &#39;Entire home/apt&#39;, &#39;Private room&#39; (optional)
     - parameter cursor: (query) next_page_cursor from a prior response (optional)
     - parameter limit: (query)  (optional, default to 18)
     - parameter currency: (query) ISO currency, e.g. USD, EUR (optional)
     - parameter locale: (query) Locale, e.g. en, fr (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func airbnbSearchStaysWithRequestBuilder(location: String? = nil, neLat: Double? = nil, neLng: Double? = nil, swLat: Double? = nil, swLng: Double? = nil, checkIn: String? = nil, checkOut: String? = nil, adults: Int? = nil, children: Int? = nil, infants: Int? = nil, pets: Int? = nil, priceMin: Int? = nil, priceMax: Int? = nil, minBedrooms: Int? = nil, minBeds: Int? = nil, minBathrooms: Int? = nil, roomType: String? = nil, cursor: String? = nil, limit: Int? = nil, currency: String? = nil, locale: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/airbnb/search"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "location": (wrappedValue: location?.encodeToJSON(), isExplode: true),
            "ne_lat": (wrappedValue: neLat?.encodeToJSON(), isExplode: true),
            "ne_lng": (wrappedValue: neLng?.encodeToJSON(), isExplode: true),
            "sw_lat": (wrappedValue: swLat?.encodeToJSON(), isExplode: true),
            "sw_lng": (wrappedValue: swLng?.encodeToJSON(), isExplode: true),
            "check_in": (wrappedValue: checkIn?.encodeToJSON(), isExplode: true),
            "check_out": (wrappedValue: checkOut?.encodeToJSON(), isExplode: true),
            "adults": (wrappedValue: adults?.encodeToJSON(), isExplode: true),
            "children": (wrappedValue: children?.encodeToJSON(), isExplode: true),
            "infants": (wrappedValue: infants?.encodeToJSON(), isExplode: true),
            "pets": (wrappedValue: pets?.encodeToJSON(), isExplode: true),
            "price_min": (wrappedValue: priceMin?.encodeToJSON(), isExplode: true),
            "price_max": (wrappedValue: priceMax?.encodeToJSON(), isExplode: true),
            "min_bedrooms": (wrappedValue: minBedrooms?.encodeToJSON(), isExplode: true),
            "min_beds": (wrappedValue: minBeds?.encodeToJSON(), isExplode: true),
            "min_bathrooms": (wrappedValue: minBathrooms?.encodeToJSON(), isExplode: true),
            "room_type": (wrappedValue: roomType?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "currency": (wrappedValue: currency?.encodeToJSON(), isExplode: true),
            "locale": (wrappedValue: locale?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
