//
// AmazonAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AmazonAPI {

    /**
     Amazon scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonAmazonScraperHealthCheck(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonAmazonScraperHealthCheckWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Amazon scraper health check
     - GET /v1/amazon/health
     - Check health of the Amazon scraper service (accepts HEAD for UptimeRobot).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonAmazonScraperHealthCheckWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/amazon/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Amazon scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonAmazonScraperHealthCheckHead(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonAmazonScraperHealthCheckHeadWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Amazon scraper health check
     - HEAD /v1/amazon/health
     - Check health of the Amazon scraper service (accepts HEAD for UptimeRobot).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonAmazonScraperHealthCheckHeadWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/amazon/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Bestsellers by category
     
     - parameter domain: (query)  (optional, default to "com")
     - parameter category: (query) Bestsellers node id or slug (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonBestsellersByCategory(domain: String? = nil, category: String? = nil, page: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonBestsellersByCategoryWithRequestBuilder(domain: domain, category: category, page: page).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Bestsellers by category
     - GET /v1/amazon/bestsellers
     - Top-selling products for a category (browse node).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter domain: (query)  (optional, default to "com")
     - parameter category: (query) Bestsellers node id or slug (optional)
     - parameter page: (query)  (optional, default to 1)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonBestsellersByCategoryWithRequestBuilder(domain: String? = nil, category: String? = nil, page: Int? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/amazon/bestsellers"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "domain": (wrappedValue: domain?.encodeToJSON(), isExplode: true),
            "category": (wrappedValue: category?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Browse-node category listing
     
     - parameter node: (query) Amazon browse-node id 
     - parameter domain: (query)  (optional, default to "com")
     - parameter page: (query)  (optional, default to 1)
     - parameter sortBy: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonBrowseNodeCategoryListing(node: String, domain: String? = nil, page: Int? = nil, sortBy: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonBrowseNodeCategoryListingWithRequestBuilder(node: node, domain: domain, page: page, sortBy: sortBy).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Browse-node category listing
     - GET /v1/amazon/category
     - List products within an Amazon browse-node category.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter node: (query) Amazon browse-node id 
     - parameter domain: (query)  (optional, default to "com")
     - parameter page: (query)  (optional, default to 1)
     - parameter sortBy: (query)  (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonBrowseNodeCategoryListingWithRequestBuilder(node: String, domain: String? = nil, page: Int? = nil, sortBy: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/amazon/category"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "node": (wrappedValue: node.encodeToJSON(), isExplode: true),
            "domain": (wrappedValue: domain?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "sort_by": (wrappedValue: sortBy?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get all seller offers (buybox)
     
     - parameter asin: (path)  
     - parameter domain: (query)  (optional, default to "com")
     - parameter zip: (query)  (optional)
     - parameter page: (query) Offer page, 10 rows each (optional, default to 1)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonGetAllSellerOffersBuybox(asin: String, domain: String? = nil, zip: String? = nil, page: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonGetAllSellerOffersBuyboxWithRequestBuilder(asin: asin, domain: domain, zip: zip, page: page).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get all seller offers (buybox)
     - GET /v1/amazon/products/{asin}/offers
     - All third-party offers for an ASIN, including the Buy Box winner.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter asin: (path)  
     - parameter domain: (query)  (optional, default to "com")
     - parameter zip: (query)  (optional)
     - parameter page: (query) Offer page, 10 rows each (optional, default to 1)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonGetAllSellerOffersBuyboxWithRequestBuilder(asin: String, domain: String? = nil, zip: String? = nil, page: Int? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/amazon/products/{asin}/offers"
        let asinPreEscape = "\(APIHelper.mapValueToPathItem(asin))"
        let asinPostEscape = asinPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{asin}", with: asinPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "domain": (wrappedValue: domain?.encodeToJSON(), isExplode: true),
            "zip": (wrappedValue: zip?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get product detail
     
     - parameter asin: (path)  
     - parameter domain: (query)  (optional, default to "com")
     - parameter zip: (query) Delivery postal/zip for localized buybox (optional)
     - parameter language: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonGetProductDetail(asin: String, domain: String? = nil, zip: String? = nil, language: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonGetProductDetailWithRequestBuilder(asin: asin, domain: domain, zip: zip, language: language).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get product detail
     - GET /v1/amazon/products/{asin}
     - Full product detail by ASIN (price, variants, badges, buybox, ranks…).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter asin: (path)  
     - parameter domain: (query)  (optional, default to "com")
     - parameter zip: (query) Delivery postal/zip for localized buybox (optional)
     - parameter language: (query)  (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonGetProductDetailWithRequestBuilder(asin: String, domain: String? = nil, zip: String? = nil, language: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/amazon/products/{asin}"
        let asinPreEscape = "\(APIHelper.mapValueToPathItem(asin))"
        let asinPostEscape = asinPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{asin}", with: asinPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "domain": (wrappedValue: domain?.encodeToJSON(), isExplode: true),
            "zip": (wrappedValue: zip?.encodeToJSON(), isExplode: true),
            "language": (wrappedValue: language?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get product reviews
     
     - parameter asin: (path)  
     - parameter domain: (query)  (optional, default to "com")
     - parameter page: (query) Review page (1-100, ~10 reviews/page) (optional, default to 1)
     - parameter sortBy: (query) helpful | recent (optional, default to "helpful")
     - parameter star: (query) one_star..five_star | positive | critical (optional)
     - parameter verifiedOnly: (query)  (optional, default to false)
     - parameter mediaOnly: (query)  (optional, default to false)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonGetProductReviews(asin: String, domain: String? = nil, page: Int? = nil, sortBy: String? = nil, star: String? = nil, verifiedOnly: Bool? = nil, mediaOnly: Bool? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonGetProductReviewsWithRequestBuilder(asin: asin, domain: domain, page: page, sortBy: sortBy, star: star, verifiedOnly: verifiedOnly, mediaOnly: mediaOnly).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get product reviews
     - GET /v1/amazon/products/{asin}/reviews
     - Customer reviews for an ASIN (featured + paginated, with filters).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter asin: (path)  
     - parameter domain: (query)  (optional, default to "com")
     - parameter page: (query) Review page (1-100, ~10 reviews/page) (optional, default to 1)
     - parameter sortBy: (query) helpful | recent (optional, default to "helpful")
     - parameter star: (query) one_star..five_star | positive | critical (optional)
     - parameter verifiedOnly: (query)  (optional, default to false)
     - parameter mediaOnly: (query)  (optional, default to false)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonGetProductReviewsWithRequestBuilder(asin: String, domain: String? = nil, page: Int? = nil, sortBy: String? = nil, star: String? = nil, verifiedOnly: Bool? = nil, mediaOnly: Bool? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/amazon/products/{asin}/reviews"
        let asinPreEscape = "\(APIHelper.mapValueToPathItem(asin))"
        let asinPostEscape = asinPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{asin}", with: asinPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "domain": (wrappedValue: domain?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "sort_by": (wrappedValue: sortBy?.encodeToJSON(), isExplode: true),
            "star": (wrappedValue: star?.encodeToJSON(), isExplode: true),
            "verified_only": (wrappedValue: verifiedOnly?.encodeToJSON(), isExplode: true),
            "media_only": (wrappedValue: mediaOnly?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get seller feedback
     
     - parameter sellerId: (path)  
     - parameter domain: (query)  (optional, default to "com")
     - parameter page: (query)  (optional, default to 1)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonGetSellerFeedback(sellerId: String, domain: String? = nil, page: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonGetSellerFeedbackWithRequestBuilder(sellerId: sellerId, domain: domain, page: page).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get seller feedback
     - GET /v1/amazon/sellers/{seller_id}/feedback
     - Buyer feedback entries for a seller.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter sellerId: (path)  
     - parameter domain: (query)  (optional, default to "com")
     - parameter page: (query)  (optional, default to 1)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonGetSellerFeedbackWithRequestBuilder(sellerId: String, domain: String? = nil, page: Int? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/amazon/sellers/{seller_id}/feedback"
        let sellerIdPreEscape = "\(APIHelper.mapValueToPathItem(sellerId))"
        let sellerIdPostEscape = sellerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{seller_id}", with: sellerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "domain": (wrappedValue: domain?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get seller profile
     
     - parameter sellerId: (path)  
     - parameter domain: (query)  (optional, default to "com")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonGetSellerProfile(sellerId: String, domain: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonGetSellerProfileWithRequestBuilder(sellerId: sellerId, domain: domain).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get seller profile
     - GET /v1/amazon/sellers/{seller_id}
     - Seller profile, ratings and feedback summary.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter sellerId: (path)  
     - parameter domain: (query)  (optional, default to "com")
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonGetSellerProfileWithRequestBuilder(sellerId: String, domain: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/amazon/sellers/{seller_id}"
        let sellerIdPreEscape = "\(APIHelper.mapValueToPathItem(sellerId))"
        let sellerIdPostEscape = sellerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{seller_id}", with: sellerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "domain": (wrappedValue: domain?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get seller storefront products
     
     - parameter sellerId: (path)  
     - parameter domain: (query)  (optional, default to "com")
     - parameter page: (query)  (optional, default to 1)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonGetSellerStorefrontProducts(sellerId: String, domain: String? = nil, page: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonGetSellerStorefrontProductsWithRequestBuilder(sellerId: sellerId, domain: domain, page: page).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get seller storefront products
     - GET /v1/amazon/sellers/{seller_id}/products
     - Products listed in a seller's storefront.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter sellerId: (path)  
     - parameter domain: (query)  (optional, default to "com")
     - parameter page: (query)  (optional, default to 1)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonGetSellerStorefrontProductsWithRequestBuilder(sellerId: String, domain: String? = nil, page: Int? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/amazon/sellers/{seller_id}/products"
        let sellerIdPreEscape = "\(APIHelper.mapValueToPathItem(sellerId))"
        let sellerIdPostEscape = sellerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{seller_id}", with: sellerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "domain": (wrappedValue: domain?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Keyword suggestions
     
     - parameter query: (query) Partial search term 
     - parameter domain: (query)  (optional, default to "com")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonKeywordSuggestions(query: String, domain: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonKeywordSuggestionsWithRequestBuilder(query: query, domain: domain).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Keyword suggestions
     - GET /v1/amazon/autocomplete
     - Get Amazon search autocomplete suggestions for keyword research.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Partial search term 
     - parameter domain: (query)  (optional, default to "com")
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonKeywordSuggestionsWithRequestBuilder(query: String, domain: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/amazon/autocomplete"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
            "domain": (wrappedValue: domain?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List category aliases
     
     - parameter domain: (query)  (optional, default to "com")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonListCategoryAliases(domain: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonListCategoryAliasesWithRequestBuilder(domain: domain).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List category aliases
     - GET /v1/amazon/categories
     - List common Amazon department/category aliases and bestseller nodes.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter domain: (query)  (optional, default to "com")
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonListCategoryAliasesWithRequestBuilder(domain: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/amazon/categories"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "domain": (wrappedValue: domain?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List marketplaces
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonListMarketplaces(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonListMarketplacesWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List marketplaces
     - GET /v1/amazon/markets
     - List all supported Amazon marketplaces.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonListMarketplacesWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/amazon/markets"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     New releases by category
     
     - parameter domain: (query)  (optional, default to "com")
     - parameter category: (query)  (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonNewReleasesByCategory(domain: String? = nil, category: String? = nil, page: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonNewReleasesByCategoryWithRequestBuilder(domain: domain, category: category, page: page).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     New releases by category
     - GET /v1/amazon/new-releases
     - Newly released products for a category (browse node).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter domain: (query)  (optional, default to "com")
     - parameter category: (query)  (optional)
     - parameter page: (query)  (optional, default to 1)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonNewReleasesByCategoryWithRequestBuilder(domain: String? = nil, category: String? = nil, page: Int? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/amazon/new-releases"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "domain": (wrappedValue: domain?.encodeToJSON(), isExplode: true),
            "category": (wrappedValue: category?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search Amazon products
     
     - parameter query: (query) Search keywords 
     - parameter domain: (query) Amazon marketplace TLD or code (com, co.uk, de…) (optional, default to "com")
     - parameter page: (query)  (optional, default to 1)
     - parameter sortBy: (query) relevance | price_low_to_high | price_high_to_low | avg_review | newest (optional)
     - parameter category: (query) Department/category alias (i&#x3D; param) (optional)
     - parameter minPrice: (query)  (optional)
     - parameter maxPrice: (query)  (optional)
     - parameter zip: (query) Delivery postal/zip code for localized pricing (optional)
     - parameter language: (query) Locale for results, e.g. en_US, fr_FR (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonSearchAmazonProducts(query: String, domain: String? = nil, page: Int? = nil, sortBy: String? = nil, category: String? = nil, minPrice: Double? = nil, maxPrice: Double? = nil, zip: String? = nil, language: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonSearchAmazonProductsWithRequestBuilder(query: query, domain: domain, page: page, sortBy: sortBy, category: category, minPrice: minPrice, maxPrice: maxPrice, zip: zip, language: language).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search Amazon products
     - GET /v1/amazon/search
     - Search the Amazon catalog with filters and sorting.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Search keywords 
     - parameter domain: (query) Amazon marketplace TLD or code (com, co.uk, de…) (optional, default to "com")
     - parameter page: (query)  (optional, default to 1)
     - parameter sortBy: (query) relevance | price_low_to_high | price_high_to_low | avg_review | newest (optional)
     - parameter category: (query) Department/category alias (i&#x3D; param) (optional)
     - parameter minPrice: (query)  (optional)
     - parameter maxPrice: (query)  (optional)
     - parameter zip: (query) Delivery postal/zip code for localized pricing (optional)
     - parameter language: (query) Locale for results, e.g. en_US, fr_FR (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonSearchAmazonProductsWithRequestBuilder(query: String, domain: String? = nil, page: Int? = nil, sortBy: String? = nil, category: String? = nil, minPrice: Double? = nil, maxPrice: Double? = nil, zip: String? = nil, language: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/amazon/search"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
            "domain": (wrappedValue: domain?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "sort_by": (wrappedValue: sortBy?.encodeToJSON(), isExplode: true),
            "category": (wrappedValue: category?.encodeToJSON(), isExplode: true),
            "min_price": (wrappedValue: minPrice?.encodeToJSON(), isExplode: true),
            "max_price": (wrappedValue: maxPrice?.encodeToJSON(), isExplode: true),
            "zip": (wrappedValue: zip?.encodeToJSON(), isExplode: true),
            "language": (wrappedValue: language?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Today's deals
     
     - parameter domain: (query)  (optional, default to "com")
     - parameter category: (query)  (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func amazonTodaySDeals(domain: String? = nil, category: String? = nil, page: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return amazonTodaySDealsWithRequestBuilder(domain: domain, category: category, page: page).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Today's deals
     - GET /v1/amazon/deals
     - Current Amazon deals (lightning deals, best deals).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter domain: (query)  (optional, default to "com")
     - parameter category: (query)  (optional)
     - parameter page: (query)  (optional, default to 1)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func amazonTodaySDealsWithRequestBuilder(domain: String? = nil, category: String? = nil, page: Int? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/amazon/deals"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "domain": (wrappedValue: domain?.encodeToJSON(), isExplode: true),
            "category": (wrappedValue: category?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
