//
// BaiduAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class BaiduAPI {

    /**
     Baidu image search
     
     - parameter query: (query) Search keywords 
     - parameter page: (query) 30 images per page (optional, default to 1)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func baiduBaiduImageSearch(query: String, page: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return baiduBaiduImageSearchWithRequestBuilder(query: query, page: page).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Baidu image search
     - GET /v1/baidu/images
     - Baidu image search via the acjson JSON API.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Search keywords 
     - parameter page: (query) 30 images per page (optional, default to 1)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func baiduBaiduImageSearchWithRequestBuilder(query: String, page: Int? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/baidu/images"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Baidu news search
     
     - parameter query: (query) Search keywords 
     - parameter page: (query)  (optional, default to 1)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func baiduBaiduNewsSearch(query: String, page: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return baiduBaiduNewsSearchWithRequestBuilder(query: query, page: page).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Baidu news search
     - GET /v1/baidu/news
     - Baidu news vertical — articles with source, publish date and real URLs.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Search keywords 
     - parameter page: (query)  (optional, default to 1)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func baiduBaiduNewsSearchWithRequestBuilder(query: String, page: Int? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/baidu/news"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Baidu scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func baiduBaiduScraperHealthCheck(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return baiduBaiduScraperHealthCheckWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Baidu scraper health check
     - GET /v1/baidu/health
     - Check health of the Baidu scraper service (accepts HEAD for UptimeRobot).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func baiduBaiduScraperHealthCheckWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/baidu/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Baidu scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func baiduBaiduScraperHealthCheckHead(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return baiduBaiduScraperHealthCheckHeadWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Baidu scraper health check
     - HEAD /v1/baidu/health
     - Check health of the Baidu scraper service (accepts HEAD for UptimeRobot).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func baiduBaiduScraperHealthCheckHeadWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/baidu/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Baidu web search
     
     - parameter query: (query) Search keywords, e.g. &#39;咖啡机&#39; or &#39;coffee machine&#39; 
     - parameter page: (query) Result page (10 results per page) (optional, default to 1)
     - parameter num: (query) Results per page (rn) (optional, default to 10)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func baiduBaiduWebSearch(query: String, page: Int? = nil, num: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return baiduBaiduWebSearchWithRequestBuilder(query: query, page: page, num: num).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Baidu web search
     - GET /v1/baidu/search
     - Baidu web SERP — organic results with real target URLs, related searches, total count.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Search keywords, e.g. &#39;咖啡机&#39; or &#39;coffee machine&#39; 
     - parameter page: (query) Result page (10 results per page) (optional, default to 1)
     - parameter num: (query) Results per page (rn) (optional, default to 10)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func baiduBaiduWebSearchWithRequestBuilder(query: String, page: Int? = nil, num: Int? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/baidu/search"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "num": (wrappedValue: num?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search suggestions
     
     - parameter query: (query) Partial search term, e.g. &#39;咖啡&#39; or &#39;coff&#39; 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func baiduSearchSuggestions(query: String, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return baiduSearchSuggestionsWithRequestBuilder(query: query).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search suggestions
     - GET /v1/baidu/autocomplete
     - Baidu search-box suggestions.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Partial search term, e.g. &#39;咖啡&#39; or &#39;coff&#39; 
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func baiduSearchSuggestionsWithRequestBuilder(query: String) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/baidu/autocomplete"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
