//
// BookingAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class BookingAPI {

    /**
     Booking scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func bookingBookingScraperHealthCheck(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return bookingBookingScraperHealthCheckWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Booking scraper health check
     - GET /v1/booking/health
     - Check health of the Booking scraper service (accepts HEAD).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func bookingBookingScraperHealthCheckWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/booking/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Booking scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func bookingBookingScraperHealthCheckHead(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return bookingBookingScraperHealthCheckHeadWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Booking scraper health check
     - HEAD /v1/booking/health
     - Check health of the Booking scraper service (accepts HEAD).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func bookingBookingScraperHealthCheckHeadWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/booking/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get property detail
     
     - parameter countryCode: (path) Two-letter country code, e.g. &#39;it&#39; 
     - parameter slug: (path) Booking page name, e.g. &#39;hotel-artemide&#39; 
     - parameter photos: (query) Gallery photos to return (optional, default to 40)
     - parameter questions: (query) Guest Q&amp;A pairs to return (optional, default to 10)
     - parameter language: (query) Locale, e.g. en-us, fr (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func bookingGetPropertyDetail(countryCode: String, slug: String, photos: Int? = nil, questions: Int? = nil, language: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return bookingGetPropertyDetailWithRequestBuilder(countryCode: countryCode, slug: slug, photos: photos, questions: questions, language: language).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get property detail
     - GET /v1/booking/properties/{country_code}/{slug}
     - Full detail for one property: description, address and coordinates, star rating, review score with per-category breakdown, facilities, house rules, room types with occupancy and beds, photos and guest Q&A.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter countryCode: (path) Two-letter country code, e.g. &#39;it&#39; 
     - parameter slug: (path) Booking page name, e.g. &#39;hotel-artemide&#39; 
     - parameter photos: (query) Gallery photos to return (optional, default to 40)
     - parameter questions: (query) Guest Q&amp;A pairs to return (optional, default to 10)
     - parameter language: (query) Locale, e.g. en-us, fr (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func bookingGetPropertyDetailWithRequestBuilder(countryCode: String, slug: String, photos: Int? = nil, questions: Int? = nil, language: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/booking/properties/{country_code}/{slug}"
        let countryCodePreEscape = "\(APIHelper.mapValueToPathItem(countryCode))"
        let countryCodePostEscape = countryCodePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{country_code}", with: countryCodePostEscape, options: .literal, range: nil)
        let slugPreEscape = "\(APIHelper.mapValueToPathItem(slug))"
        let slugPostEscape = slugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slug}", with: slugPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "photos": (wrappedValue: photos?.encodeToJSON(), isExplode: true),
            "questions": (wrappedValue: questions?.encodeToJSON(), isExplode: true),
            "language": (wrappedValue: language?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get property reviews
     
     - parameter countryCode: (path) Two-letter country code, e.g. &#39;it&#39; 
     - parameter slug: (path) Booking page name, e.g. &#39;hotel-artemide&#39; 
     - parameter limit: (query)  (optional, default to 25)
     - parameter offset: (query)  (optional, default to 0)
     - parameter sort: (query) MOST_RELEVANT | NEWEST_FIRST | OLDEST_FIRST | SCORE_DESC | SCORE_ASC (optional, default to "MOST_RELEVANT")
     - parameter reviewLanguage: (query) Only reviews written in this language, e.g. &#39;fr&#39; (optional)
     - parameter guestType: (query) FAMILIES | COUPLES | GROUP_OF_FRIENDS | SOLO_TRAVELLERS | BUSINESS_TRAVELLERS (optional)
     - parameter language: (query) Locale for labels, e.g. en-us (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func bookingGetPropertyReviews(countryCode: String, slug: String, limit: Int? = nil, offset: Int? = nil, sort: String? = nil, reviewLanguage: String? = nil, guestType: String? = nil, language: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return bookingGetPropertyReviewsWithRequestBuilder(countryCode: countryCode, slug: slug, limit: limit, offset: offset, sort: sort, reviewLanguage: reviewLanguage, guestType: guestType, language: language).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get property reviews
     - GET /v1/booking/properties/{country_code}/{slug}/reviews
     - Paginated guest reviews with score, positive and negative text, stay dates, room type, guest country and type, photos and the partner's reply.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter countryCode: (path) Two-letter country code, e.g. &#39;it&#39; 
     - parameter slug: (path) Booking page name, e.g. &#39;hotel-artemide&#39; 
     - parameter limit: (query)  (optional, default to 25)
     - parameter offset: (query)  (optional, default to 0)
     - parameter sort: (query) MOST_RELEVANT | NEWEST_FIRST | OLDEST_FIRST | SCORE_DESC | SCORE_ASC (optional, default to "MOST_RELEVANT")
     - parameter reviewLanguage: (query) Only reviews written in this language, e.g. &#39;fr&#39; (optional)
     - parameter guestType: (query) FAMILIES | COUPLES | GROUP_OF_FRIENDS | SOLO_TRAVELLERS | BUSINESS_TRAVELLERS (optional)
     - parameter language: (query) Locale for labels, e.g. en-us (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func bookingGetPropertyReviewsWithRequestBuilder(countryCode: String, slug: String, limit: Int? = nil, offset: Int? = nil, sort: String? = nil, reviewLanguage: String? = nil, guestType: String? = nil, language: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/booking/properties/{country_code}/{slug}/reviews"
        let countryCodePreEscape = "\(APIHelper.mapValueToPathItem(countryCode))"
        let countryCodePostEscape = countryCodePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{country_code}", with: countryCodePostEscape, options: .literal, range: nil)
        let slugPreEscape = "\(APIHelper.mapValueToPathItem(slug))"
        let slugPostEscape = slugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slug}", with: slugPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
            "review_language": (wrappedValue: reviewLanguage?.encodeToJSON(), isExplode: true),
            "guest_type": (wrappedValue: guestType?.encodeToJSON(), isExplode: true),
            "language": (wrappedValue: language?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search destinations
     
     - parameter query: (query) Free-text place, e.g. &#39;amsterd&#39; 
     - parameter limit: (query)  (optional, default to 8)
     - parameter language: (query) Locale, e.g. en-us, fr (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func bookingSearchDestinations(query: String, limit: Int? = nil, language: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return bookingSearchDestinationsWithRequestBuilder(query: query, limit: limit, language: language).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search destinations
     - GET /v1/booking/destinations
     - Resolve a place name to Booking's `dest_id`/`dest_type`, with coordinates and country — feed the pair back into /search for an exact match.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Free-text place, e.g. &#39;amsterd&#39; 
     - parameter limit: (query)  (optional, default to 8)
     - parameter language: (query) Locale, e.g. en-us, fr (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func bookingSearchDestinationsWithRequestBuilder(query: String, limit: Int? = nil, language: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/booking/destinations"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "language": (wrappedValue: language?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search properties
     
     - parameter location: (query) Free-text destination, e.g. &#39;Rome&#39; (optional)
     - parameter destId: (query) Exact destination id (ufi) from /destinations (optional)
     - parameter destType: (query) Destination type, e.g. CITY (optional, default to "NO_DEST_TYPE")
     - parameter checkin: (query) Check-in date YYYY-MM-DD (optional)
     - parameter checkout: (query) Check-out date YYYY-MM-DD (optional)
     - parameter adults: (query)  (optional, default to 2)
     - parameter children: (query) Comma-separated children ages, e.g. &#39;4,9&#39; (optional)
     - parameter rooms: (query)  (optional, default to 1)
     - parameter offset: (query) Result offset for pagination (optional, default to 0)
     - parameter limit: (query)  (optional, default to 25)
     - parameter sort: (query) popularity | price | class_descending | class_ascending | distance_from_search | bayesian_review_score | review_score_and_price | upsort_bh (optional)
     - parameter filters: (query) Semicolon-separated Booking filter ids, e.g. &#39;class&#x3D;4&#39; (optional)
     - parameter currency: (query) ISO currency, e.g. EUR, USD, GBP (optional)
     - parameter language: (query) Locale, e.g. en-us, fr, de, es (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func bookingSearchProperties(location: String? = nil, destId: Int? = nil, destType: String? = nil, checkin: String? = nil, checkout: String? = nil, adults: Int? = nil, children: String? = nil, rooms: Int? = nil, offset: Int? = nil, limit: Int? = nil, sort: String? = nil, filters: String? = nil, currency: String? = nil, language: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return bookingSearchPropertiesWithRequestBuilder(location: location, destId: destId, destType: destType, checkin: checkin, checkout: checkout, adults: adults, children: children, rooms: rooms, offset: offset, limit: limit, sort: sort, filters: filters, currency: currency, language: language).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search properties
     - GET /v1/booking/search
     - Search Booking.com properties by destination, with dates, occupancy, sorting and filters. Returns prices, review scores, coordinates, room configuration and photos. Paginate with `offset`.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter location: (query) Free-text destination, e.g. &#39;Rome&#39; (optional)
     - parameter destId: (query) Exact destination id (ufi) from /destinations (optional)
     - parameter destType: (query) Destination type, e.g. CITY (optional, default to "NO_DEST_TYPE")
     - parameter checkin: (query) Check-in date YYYY-MM-DD (optional)
     - parameter checkout: (query) Check-out date YYYY-MM-DD (optional)
     - parameter adults: (query)  (optional, default to 2)
     - parameter children: (query) Comma-separated children ages, e.g. &#39;4,9&#39; (optional)
     - parameter rooms: (query)  (optional, default to 1)
     - parameter offset: (query) Result offset for pagination (optional, default to 0)
     - parameter limit: (query)  (optional, default to 25)
     - parameter sort: (query) popularity | price | class_descending | class_ascending | distance_from_search | bayesian_review_score | review_score_and_price | upsort_bh (optional)
     - parameter filters: (query) Semicolon-separated Booking filter ids, e.g. &#39;class&#x3D;4&#39; (optional)
     - parameter currency: (query) ISO currency, e.g. EUR, USD, GBP (optional)
     - parameter language: (query) Locale, e.g. en-us, fr, de, es (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func bookingSearchPropertiesWithRequestBuilder(location: String? = nil, destId: Int? = nil, destType: String? = nil, checkin: String? = nil, checkout: String? = nil, adults: Int? = nil, children: String? = nil, rooms: Int? = nil, offset: Int? = nil, limit: Int? = nil, sort: String? = nil, filters: String? = nil, currency: String? = nil, language: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/booking/search"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "location": (wrappedValue: location?.encodeToJSON(), isExplode: true),
            "dest_id": (wrappedValue: destId?.encodeToJSON(), isExplode: true),
            "dest_type": (wrappedValue: destType?.encodeToJSON(), isExplode: true),
            "checkin": (wrappedValue: checkin?.encodeToJSON(), isExplode: true),
            "checkout": (wrappedValue: checkout?.encodeToJSON(), isExplode: true),
            "adults": (wrappedValue: adults?.encodeToJSON(), isExplode: true),
            "children": (wrappedValue: children?.encodeToJSON(), isExplode: true),
            "rooms": (wrappedValue: rooms?.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
            "filters": (wrappedValue: filters?.encodeToJSON(), isExplode: true),
            "currency": (wrappedValue: currency?.encodeToJSON(), isExplode: true),
            "language": (wrappedValue: language?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
