//
// DepopAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class DepopAPI {

    /**
     Depop scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func depopDepopScraperHealthCheck(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return depopDepopScraperHealthCheckWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Depop scraper health check
     - GET /v1/depop/health
     - Check health of the Depop scraper service (accepts HEAD).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func depopDepopScraperHealthCheckWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/depop/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Depop scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func depopDepopScraperHealthCheckHead(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return depopDepopScraperHealthCheckHeadWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Depop scraper health check
     - HEAD /v1/depop/health
     - Check health of the Depop scraper service (accepts HEAD).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func depopDepopScraperHealthCheckHeadWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/depop/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get a user's products
     
     - parameter username: (path)  
     - parameter market: (query) Market code (optional, default to "us")
     - parameter perPage: (query)  (optional, default to 24)
     - parameter cursor: (query) Pagination cursor (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func depopGetAUserSProducts(username: String, market: String? = nil, perPage: Int? = nil, cursor: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return depopGetAUserSProductsWithRequestBuilder(username: username, market: market, perPage: perPage, cursor: cursor).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get a user's products
     - GET /v1/depop/users/{username}/products
     - A user's active listings (cursor-paginated).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter username: (path)  
     - parameter market: (query) Market code (optional, default to "us")
     - parameter perPage: (query)  (optional, default to 24)
     - parameter cursor: (query) Pagination cursor (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func depopGetAUserSProductsWithRequestBuilder(username: String, market: String? = nil, perPage: Int? = nil, cursor: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/depop/users/{username}/products"
        let usernamePreEscape = "\(APIHelper.mapValueToPathItem(username))"
        let usernamePostEscape = usernamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{username}", with: usernamePostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "market": (wrappedValue: market?.encodeToJSON(), isExplode: true),
            "per_page": (wrappedValue: perPage?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get product detail
     
     - parameter productId: (path)  
     - parameter market: (query) Market code (optional, default to "us")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func depopGetProductDetail(productId: String, market: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return depopGetProductDetailWithRequestBuilder(productId: productId, market: market).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get product detail
     - GET /v1/depop/products/{product_id}
     - Full detail for a single product (by numeric id or slug).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter productId: (path)  
     - parameter market: (query) Market code (optional, default to "us")
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func depopGetProductDetailWithRequestBuilder(productId: String, market: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/depop/products/{product_id}"
        let productIdPreEscape = "\(APIHelper.mapValueToPathItem(productId))"
        let productIdPostEscape = productIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{product_id}", with: productIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "market": (wrappedValue: market?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get shop/user profile
     
     - parameter username: (path)  
     - parameter market: (query) Market code (optional, default to "us")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func depopGetShopUserProfile(username: String, market: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return depopGetShopUserProfileWithRequestBuilder(username: username, market: market).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get shop/user profile
     - GET /v1/depop/users/{username}
     - Public shop/user profile by username.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter username: (path)  
     - parameter market: (query) Market code (optional, default to "us")
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func depopGetShopUserProfileWithRequestBuilder(username: String, market: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/depop/users/{username}"
        let usernamePreEscape = "\(APIHelper.mapValueToPathItem(username))"
        let usernamePostEscape = usernamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{username}", with: usernamePostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "market": (wrappedValue: market?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List markets
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func depopListMarkets(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return depopListMarketsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List markets
     - GET /v1/depop/markets
     - List supported Depop markets (country + currency).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func depopListMarketsWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/depop/markets"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search Depop products
     
     - parameter query: (query) Search text, e.g. &#39;nike vintage&#39; 
     - parameter market: (query) Market code (us, gb, au, it, fr, ...) (optional, default to "us")
     - parameter perPage: (query) Results per page (optional, default to 24)
     - parameter cursor: (query) Pagination cursor (from previous page) (optional)
     - parameter priceMin: (query) Minimum price (optional)
     - parameter priceMax: (query) Maximum price (optional)
     - parameter brands: (query) Comma-separated brand IDs (optional)
     - parameter categories: (query) Comma-separated category IDs (optional)
     - parameter sizes: (query) Comma-separated size IDs (optional)
     - parameter conditions: (query) Comma-separated condition slugs (brand_new, used_excellent, ...) (optional)
     - parameter gender: (query) male | female (optional)
     - parameter sort: (query) relevance | newlyListed | priceAscending | priceDescending (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func depopSearchDepopProducts(query: String, market: String? = nil, perPage: Int? = nil, cursor: String? = nil, priceMin: Double? = nil, priceMax: Double? = nil, brands: String? = nil, categories: String? = nil, sizes: String? = nil, conditions: String? = nil, gender: String? = nil, sort: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return depopSearchDepopProductsWithRequestBuilder(query: query, market: market, perPage: perPage, cursor: cursor, priceMin: priceMin, priceMax: priceMax, brands: brands, categories: categories, sizes: sizes, conditions: conditions, gender: gender, sort: sort).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search Depop products
     - GET /v1/depop/search
     - Search the Depop catalog with filters (cursor-paginated).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Search text, e.g. &#39;nike vintage&#39; 
     - parameter market: (query) Market code (us, gb, au, it, fr, ...) (optional, default to "us")
     - parameter perPage: (query) Results per page (optional, default to 24)
     - parameter cursor: (query) Pagination cursor (from previous page) (optional)
     - parameter priceMin: (query) Minimum price (optional)
     - parameter priceMax: (query) Maximum price (optional)
     - parameter brands: (query) Comma-separated brand IDs (optional)
     - parameter categories: (query) Comma-separated category IDs (optional)
     - parameter sizes: (query) Comma-separated size IDs (optional)
     - parameter conditions: (query) Comma-separated condition slugs (brand_new, used_excellent, ...) (optional)
     - parameter gender: (query) male | female (optional)
     - parameter sort: (query) relevance | newlyListed | priceAscending | priceDescending (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func depopSearchDepopProductsWithRequestBuilder(query: String, market: String? = nil, perPage: Int? = nil, cursor: String? = nil, priceMin: Double? = nil, priceMax: Double? = nil, brands: String? = nil, categories: String? = nil, sizes: String? = nil, conditions: String? = nil, gender: String? = nil, sort: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/depop/search"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
            "market": (wrappedValue: market?.encodeToJSON(), isExplode: true),
            "per_page": (wrappedValue: perPage?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
            "price_min": (wrappedValue: priceMin?.encodeToJSON(), isExplode: true),
            "price_max": (wrappedValue: priceMax?.encodeToJSON(), isExplode: true),
            "brands": (wrappedValue: brands?.encodeToJSON(), isExplode: true),
            "categories": (wrappedValue: categories?.encodeToJSON(), isExplode: true),
            "sizes": (wrappedValue: sizes?.encodeToJSON(), isExplode: true),
            "conditions": (wrappedValue: conditions?.encodeToJSON(), isExplode: true),
            "gender": (wrappedValue: gender?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
