//
// LoopNetAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class LoopNetAPI {

    /**
     Get broker profile
     
     - parameter slug: (path)  
     - parameter brokerId: (path)  
     - parameter market: (query) us|ca|uk|fr|es (optional, default to "us")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func loopnetGetBrokerProfile(slug: String, brokerId: String, market: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return loopnetGetBrokerProfileWithRequestBuilder(slug: slug, brokerId: brokerId, market: market).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get broker profile
     - GET /v1/loopnet/brokers/{slug}/{broker_id}
     - Get a LoopNet broker profile + their listings by slug + id.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter slug: (path)  
     - parameter brokerId: (path)  
     - parameter market: (query) us|ca|uk|fr|es (optional, default to "us")
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func loopnetGetBrokerProfileWithRequestBuilder(slug: String, brokerId: String, market: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/loopnet/brokers/{slug}/{broker_id}"
        let slugPreEscape = "\(APIHelper.mapValueToPathItem(slug))"
        let slugPostEscape = slugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slug}", with: slugPostEscape, options: .literal, range: nil)
        let brokerIdPreEscape = "\(APIHelper.mapValueToPathItem(brokerId))"
        let brokerIdPostEscape = brokerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{broker_id}", with: brokerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "market": (wrappedValue: market?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get listing detail
     
     - parameter listingId: (path)  
     - parameter market: (query) us|ca|uk|fr|es (optional, default to "us")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func loopnetGetListingDetail(listingId: String, market: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return loopnetGetListingDetailWithRequestBuilder(listingId: listingId, market: market).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get listing detail
     - GET /v1/loopnet/listings/{listing_id}
     - Get a single LoopNet listing's full detail by its numeric id.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter listingId: (path)  
     - parameter market: (query) us|ca|uk|fr|es (optional, default to "us")
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func loopnetGetListingDetailWithRequestBuilder(listingId: String, market: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/loopnet/listings/{listing_id}"
        let listingIdPreEscape = "\(APIHelper.mapValueToPathItem(listingId))"
        let listingIdPostEscape = listingIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{listing_id}", with: listingIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "market": (wrappedValue: market?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List coverage markets
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func loopnetListCoverageMarkets(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return loopnetListCoverageMarketsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List coverage markets
     - GET /v1/loopnet/markets
     - List LoopNet coverage markets (US, CA, UK, FR, ES).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func loopnetListCoverageMarketsWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/loopnet/markets"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List property types
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func loopnetListPropertyTypes(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return loopnetListPropertyTypesWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List property types
     - GET /v1/loopnet/property-types
     - List LoopNet property-type facets accepted by /search.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func loopnetListPropertyTypesWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/loopnet/property-types"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     LoopNet scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func loopnetLoopnetScraperHealthCheck(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return loopnetLoopnetScraperHealthCheckWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     LoopNet scraper health check
     - GET /v1/loopnet/health
     - Check health of the LoopNet scraper service (accepts HEAD for UptimeRobot).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func loopnetLoopnetScraperHealthCheckWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/loopnet/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     LoopNet scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func loopnetLoopnetScraperHealthCheckHead(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return loopnetLoopnetScraperHealthCheckHeadWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     LoopNet scraper health check
     - HEAD /v1/loopnet/health
     - Check health of the LoopNet scraper service (accepts HEAD for UptimeRobot).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func loopnetLoopnetScraperHealthCheckHeadWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/loopnet/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search commercial real estate
     
     - parameter location: (query) City/state, ZIP, state code, or &#39;usa&#39; 
     - parameter market: (query) us|ca|uk|fr|es (optional, default to "us")
     - parameter listingType: (query) for-lease|for-sale|auctions (optional, default to "for-lease")
     - parameter propertyType: (query) Slug from /property-types (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter minPrice: (query)  (optional)
     - parameter maxPrice: (query)  (optional)
     - parameter priceType: (query) unit | sf | acre (optional)
     - parameter minSize: (query)  (optional)
     - parameter maxSize: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func loopnetSearchCommercialRealEstate(location: String, market: String? = nil, listingType: String? = nil, propertyType: String? = nil, page: Int? = nil, minPrice: Int? = nil, maxPrice: Int? = nil, priceType: String? = nil, minSize: Int? = nil, maxSize: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return loopnetSearchCommercialRealEstateWithRequestBuilder(location: location, market: market, listingType: listingType, propertyType: propertyType, page: page, minPrice: minPrice, maxPrice: maxPrice, priceType: priceType, minSize: minSize, maxSize: maxSize).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search commercial real estate
     - GET /v1/loopnet/search
     - Search LoopNet for-lease / for-sale / auction listings across all markets.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter location: (query) City/state, ZIP, state code, or &#39;usa&#39; 
     - parameter market: (query) us|ca|uk|fr|es (optional, default to "us")
     - parameter listingType: (query) for-lease|for-sale|auctions (optional, default to "for-lease")
     - parameter propertyType: (query) Slug from /property-types (optional)
     - parameter page: (query)  (optional, default to 1)
     - parameter minPrice: (query)  (optional)
     - parameter maxPrice: (query)  (optional)
     - parameter priceType: (query) unit | sf | acre (optional)
     - parameter minSize: (query)  (optional)
     - parameter maxSize: (query)  (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func loopnetSearchCommercialRealEstateWithRequestBuilder(location: String, market: String? = nil, listingType: String? = nil, propertyType: String? = nil, page: Int? = nil, minPrice: Int? = nil, maxPrice: Int? = nil, priceType: String? = nil, minSize: Int? = nil, maxSize: Int? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/loopnet/search"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "location": (wrappedValue: location.encodeToJSON(), isExplode: true),
            "market": (wrappedValue: market?.encodeToJSON(), isExplode: true),
            "listing_type": (wrappedValue: listingType?.encodeToJSON(), isExplode: true),
            "property_type": (wrappedValue: propertyType?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "min_price": (wrappedValue: minPrice?.encodeToJSON(), isExplode: true),
            "max_price": (wrappedValue: maxPrice?.encodeToJSON(), isExplode: true),
            "price_type": (wrappedValue: priceType?.encodeToJSON(), isExplode: true),
            "min_size": (wrappedValue: minSize?.encodeToJSON(), isExplode: true),
            "max_size": (wrappedValue: maxSize?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
