//
// PerplexityAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PerplexityAPI {

    /**
     Ask Perplexity a question
     
     - parameter prompt: (query) The prompt to send to Perplexity (max 4096 characters). 
     - parameter country: (query) ISO-3166 alpha-2 egress country, e.g. &#39;US&#39;, &#39;GB&#39;, &#39;DE&#39;. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func perplexityAskPerplexityAQuestion(prompt: String, country: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return perplexityAskPerplexityAQuestionWithRequestBuilder(prompt: prompt, country: country).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Ask Perplexity a question
     - GET /v1/perplexity/ask
     - Send a prompt to Perplexity and get the answer plus the web sources it cited.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter prompt: (query) The prompt to send to Perplexity (max 4096 characters). 
     - parameter country: (query) ISO-3166 alpha-2 egress country, e.g. &#39;US&#39;, &#39;GB&#39;, &#39;DE&#39;. (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func perplexityAskPerplexityAQuestionWithRequestBuilder(prompt: String, country: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/perplexity/ask"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "prompt": (wrappedValue: prompt.encodeToJSON(), isExplode: true),
            "country": (wrappedValue: country?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Ask Perplexity a question (POST)
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func perplexityAskPerplexityAQuestionPost(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return perplexityAskPerplexityAQuestionPostWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Ask Perplexity a question (POST)
     - POST /v1/perplexity/ask
     - POST form of `/ask`, for prompts too long for a query string.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func perplexityAskPerplexityAQuestionPostWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/perplexity/ask"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Measure a brand's visibility in a Perplexity answer
     
     - parameter prompt: (query) The prompt to ask Perplexity. 
     - parameter brand: (query) Brand name to look for in the answer. 
     - parameter domain: (query) Brand domain, for citation matching. (optional)
     - parameter aliases: (query) Comma-separated alternative names. (optional)
     - parameter competitors: (query) Comma-separated competitor names. (optional)
     - parameter country: (query) ISO-3166 alpha-2 egress country. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func perplexityMeasureABrandSVisibilityInAPerplexityAnswer(prompt: String, brand: String, domain: String? = nil, aliases: String? = nil, competitors: String? = nil, country: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return perplexityMeasureABrandSVisibilityInAPerplexityAnswerWithRequestBuilder(prompt: prompt, brand: brand, domain: domain, aliases: aliases, competitors: competitors, country: country).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Measure a brand's visibility in a Perplexity answer
     - GET /v1/perplexity/brand-visibility
     - Ask Perplexity, then report whether the brand is mentioned, cited and how prominently.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter prompt: (query) The prompt to ask Perplexity. 
     - parameter brand: (query) Brand name to look for in the answer. 
     - parameter domain: (query) Brand domain, for citation matching. (optional)
     - parameter aliases: (query) Comma-separated alternative names. (optional)
     - parameter competitors: (query) Comma-separated competitor names. (optional)
     - parameter country: (query) ISO-3166 alpha-2 egress country. (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func perplexityMeasureABrandSVisibilityInAPerplexityAnswerWithRequestBuilder(prompt: String, brand: String, domain: String? = nil, aliases: String? = nil, competitors: String? = nil, country: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/perplexity/brand-visibility"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "prompt": (wrappedValue: prompt.encodeToJSON(), isExplode: true),
            "brand": (wrappedValue: brand.encodeToJSON(), isExplode: true),
            "domain": (wrappedValue: domain?.encodeToJSON(), isExplode: true),
            "aliases": (wrappedValue: aliases?.encodeToJSON(), isExplode: true),
            "competitors": (wrappedValue: competitors?.encodeToJSON(), isExplode: true),
            "country": (wrappedValue: country?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Measure a brand's visibility in a Perplexity answer (POST)
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return perplexityMeasureABrandSVisibilityInAPerplexityAnswerPostWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Measure a brand's visibility in a Perplexity answer (POST)
     - POST /v1/perplexity/brand-visibility
     - POST form, for longer prompts and larger competitor sets.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func perplexityMeasureABrandSVisibilityInAPerplexityAnswerPostWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/perplexity/brand-visibility"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Perplexity scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func perplexityPerplexityScraperHealthCheck(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return perplexityPerplexityScraperHealthCheckWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Perplexity scraper health check
     - GET /v1/perplexity/health
     - Check health of the Perplexity scraper service (accepts HEAD).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func perplexityPerplexityScraperHealthCheckWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/perplexity/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Perplexity scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func perplexityPerplexityScraperHealthCheckHead(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return perplexityPerplexityScraperHealthCheckHeadWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Perplexity scraper health check
     - HEAD /v1/perplexity/health
     - Check health of the Perplexity scraper service (accepts HEAD).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func perplexityPerplexityScraperHealthCheckHeadWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/perplexity/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
