//
// RealtorAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RealtorAPI {

    /**
     Get full property detail
     
     - parameter propertyId: (path)  
     - parameter market: (query) us (realtor.com) | ca (realtor.ca) (optional, default to "us")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func realtorGetFullPropertyDetail(propertyId: String, market: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return realtorGetFullPropertyDetailWithRequestBuilder(propertyId: propertyId, market: market).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get full property detail
     - GET /v1/realtor/properties/{property_id}
     - Full listing detail: features, tax & price history, schools, photos, agents.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter propertyId: (path)  
     - parameter market: (query) us (realtor.com) | ca (realtor.ca) (optional, default to "us")
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func realtorGetFullPropertyDetailWithRequestBuilder(propertyId: String, market: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/realtor/properties/{property_id}"
        let propertyIdPreEscape = "\(APIHelper.mapValueToPathItem(propertyId))"
        let propertyIdPostEscape = propertyIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{property_id}", with: propertyIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "market": (wrappedValue: market?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List markets
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func realtorListMarkets(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return realtorListMarketsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List markets
     - GET /v1/realtor/markets
     - List supported Realtor markets (US = realtor.com, CA = realtor.ca).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func realtorListMarketsWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/realtor/markets"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Location autocomplete
     
     - parameter query: (query) Freetext location (city, ZIP/postal, address…) 
     - parameter market: (query) us (realtor.com) | ca (realtor.ca) (optional, default to "us")
     - parameter limit: (query)  (optional, default to 10)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func realtorLocationAutocomplete(query: String, market: String? = nil, limit: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return realtorLocationAutocompleteWithRequestBuilder(query: query, market: market, limit: limit).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Location autocomplete
     - GET /v1/realtor/autocomplete
     - Resolve a location query into candidate places to feed /search.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Freetext location (city, ZIP/postal, address…) 
     - parameter market: (query) us (realtor.com) | ca (realtor.ca) (optional, default to "us")
     - parameter limit: (query)  (optional, default to 10)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func realtorLocationAutocompleteWithRequestBuilder(query: String, market: String? = nil, limit: Int? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/realtor/autocomplete"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
            "market": (wrappedValue: market?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Realtor scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func realtorRealtorScraperHealthCheck(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return realtorRealtorScraperHealthCheckWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Realtor scraper health check
     - GET /v1/realtor/health
     - Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func realtorRealtorScraperHealthCheckWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/realtor/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Realtor scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func realtorRealtorScraperHealthCheckHead(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return realtorRealtorScraperHealthCheckHeadWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Realtor scraper health check
     - HEAD /v1/realtor/health
     - Check health of the realtor scraper service (accepts HEAD for UptimeRobot).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func realtorRealtorScraperHealthCheckHeadWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/realtor/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search property listings
     
     - parameter location: (query) &#39;Austin, TX&#39;, a ZIP, &#39;Toronto, ON&#39;… (optional)
     - parameter market: (query) us (realtor.com) | ca (realtor.ca) (optional, default to "us")
     - parameter status: (query) for_sale | for_rent | sold | pending (optional, default to "for_sale")
     - parameter priceMin: (query)  (optional)
     - parameter priceMax: (query)  (optional)
     - parameter bedsMin: (query)  (optional)
     - parameter bathsMin: (query)  (optional)
     - parameter sqftMin: (query) US only (optional)
     - parameter sqftMax: (query) US only (optional)
     - parameter propertyType: (query) US only, CSV of property types (optional)
     - parameter sort: (query) relevant | newest | price_low | price_high | photo_count (optional, default to "relevant")
     - parameter page: (query)  (optional, default to 1)
     - parameter limit: (query)  (optional)
     - parameter latMin: (query) CA bbox south (optional)
     - parameter latMax: (query) CA bbox north (optional)
     - parameter lngMin: (query) CA bbox west (optional)
     - parameter lngMax: (query) CA bbox east (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func realtorSearchPropertyListings(location: String? = nil, market: String? = nil, status: String? = nil, priceMin: Double? = nil, priceMax: Double? = nil, bedsMin: Int? = nil, bathsMin: Int? = nil, sqftMin: Int? = nil, sqftMax: Int? = nil, propertyType: String? = nil, sort: String? = nil, page: Int? = nil, limit: Int? = nil, latMin: Double? = nil, latMax: Double? = nil, lngMin: Double? = nil, lngMax: Double? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return realtorSearchPropertyListingsWithRequestBuilder(location: location, market: market, status: status, priceMin: priceMin, priceMax: priceMax, bedsMin: bedsMin, bathsMin: bathsMin, sqftMin: sqftMin, sqftMax: sqftMax, propertyType: propertyType, sort: sort, page: page, limit: limit, latMin: latMin, latMax: latMax, lngMin: lngMin, lngMax: lngMax).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search property listings
     - GET /v1/realtor/search
     - Search for-sale/for-rent/sold listings with rich filters.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter location: (query) &#39;Austin, TX&#39;, a ZIP, &#39;Toronto, ON&#39;… (optional)
     - parameter market: (query) us (realtor.com) | ca (realtor.ca) (optional, default to "us")
     - parameter status: (query) for_sale | for_rent | sold | pending (optional, default to "for_sale")
     - parameter priceMin: (query)  (optional)
     - parameter priceMax: (query)  (optional)
     - parameter bedsMin: (query)  (optional)
     - parameter bathsMin: (query)  (optional)
     - parameter sqftMin: (query) US only (optional)
     - parameter sqftMax: (query) US only (optional)
     - parameter propertyType: (query) US only, CSV of property types (optional)
     - parameter sort: (query) relevant | newest | price_low | price_high | photo_count (optional, default to "relevant")
     - parameter page: (query)  (optional, default to 1)
     - parameter limit: (query)  (optional)
     - parameter latMin: (query) CA bbox south (optional)
     - parameter latMax: (query) CA bbox north (optional)
     - parameter lngMin: (query) CA bbox west (optional)
     - parameter lngMax: (query) CA bbox east (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func realtorSearchPropertyListingsWithRequestBuilder(location: String? = nil, market: String? = nil, status: String? = nil, priceMin: Double? = nil, priceMax: Double? = nil, bedsMin: Int? = nil, bathsMin: Int? = nil, sqftMin: Int? = nil, sqftMax: Int? = nil, propertyType: String? = nil, sort: String? = nil, page: Int? = nil, limit: Int? = nil, latMin: Double? = nil, latMax: Double? = nil, lngMin: Double? = nil, lngMax: Double? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/realtor/search"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "location": (wrappedValue: location?.encodeToJSON(), isExplode: true),
            "market": (wrappedValue: market?.encodeToJSON(), isExplode: true),
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
            "price_min": (wrappedValue: priceMin?.encodeToJSON(), isExplode: true),
            "price_max": (wrappedValue: priceMax?.encodeToJSON(), isExplode: true),
            "beds_min": (wrappedValue: bedsMin?.encodeToJSON(), isExplode: true),
            "baths_min": (wrappedValue: bathsMin?.encodeToJSON(), isExplode: true),
            "sqft_min": (wrappedValue: sqftMin?.encodeToJSON(), isExplode: true),
            "sqft_max": (wrappedValue: sqftMax?.encodeToJSON(), isExplode: true),
            "property_type": (wrappedValue: propertyType?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "lat_min": (wrappedValue: latMin?.encodeToJSON(), isExplode: true),
            "lat_max": (wrappedValue: latMax?.encodeToJSON(), isExplode: true),
            "lng_min": (wrappedValue: lngMin?.encodeToJSON(), isExplode: true),
            "lng_max": (wrappedValue: lngMax?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
