//
// RedfinAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RedfinAPI {

    /**
     Get agent profile + listings
     
     - parameter url: (query) Full Redfin /realestateagents/ URL (optional)
     - parameter agentId: (query) Redfin agent id (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func redfinGetAgentProfileListings(url: String? = nil, agentId: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return redfinGetAgentProfileListingsWithRequestBuilder(url: url, agentId: agentId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get agent profile + listings
     - GET /v1/redfin/agent
     - Get a Redfin real-estate agent's profile and their active listings.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter url: (query) Full Redfin /realestateagents/ URL (optional)
     - parameter agentId: (query) Redfin agent id (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func redfinGetAgentProfileListingsWithRequestBuilder(url: String? = nil, agentId: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/redfin/agent"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "url": (wrappedValue: url?.encodeToJSON(), isExplode: true),
            "agent_id": (wrappedValue: agentId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get property detail
     
     - parameter propertyId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func redfinGetPropertyDetail(propertyId: String, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return redfinGetPropertyDetailWithRequestBuilder(propertyId: propertyId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get property detail
     - GET /v1/redfin/property/{property_id}
     - Get a single Redfin property's full detail by its numeric propertyId.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter propertyId: (path)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func redfinGetPropertyDetailWithRequestBuilder(propertyId: String) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/redfin/property/{property_id}"
        let propertyIdPreEscape = "\(APIHelper.mapValueToPathItem(propertyId))"
        let propertyIdPostEscape = propertyIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{property_id}", with: propertyIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get property detail by URL
     
     - parameter url: (query) Full Redfin property URL (/CA/City/.../home/12345678) 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func redfinGetPropertyDetailByUrl(url: String, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return redfinGetPropertyDetailByUrlWithRequestBuilder(url: url).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get property detail by URL
     - GET /v1/redfin/property
     - Get a single Redfin property's full detail by its home URL.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter url: (query) Full Redfin property URL (/CA/City/.../home/12345678) 
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func redfinGetPropertyDetailByUrlWithRequestBuilder(url: String) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/redfin/property"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "url": (wrappedValue: url.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List coverage markets
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func redfinListCoverageMarkets(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return redfinListCoverageMarketsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List coverage markets
     - GET /v1/redfin/markets
     - List Redfin coverage regions (US).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func redfinListCoverageMarketsWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/redfin/markets"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Redfin scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func redfinRedfinScraperHealthCheck(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return redfinRedfinScraperHealthCheckWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Redfin scraper health check
     - GET /v1/redfin/health
     - Check health of the Redfin scraper service (accepts HEAD for UptimeRobot).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func redfinRedfinScraperHealthCheckWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/redfin/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Redfin scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func redfinRedfinScraperHealthCheckHead(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return redfinRedfinScraperHealthCheckHeadWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Redfin scraper health check
     - HEAD /v1/redfin/health
     - Check health of the Redfin scraper service (accepts HEAD for UptimeRobot).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func redfinRedfinScraperHealthCheckHeadWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/redfin/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Region/address suggestions
     
     - parameter query: (query) Partial location — city, ZIP, address, neighborhood 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func redfinRegionAddressSuggestions(query: String, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return redfinRegionAddressSuggestionsWithRequestBuilder(query: query).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Region/address suggestions
     - GET /v1/redfin/autocomplete
     - Resolve a search term to Redfin regions/addresses.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Partial location — city, ZIP, address, neighborhood 
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func redfinRegionAddressSuggestionsWithRequestBuilder(query: String) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/redfin/autocomplete"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search properties
     
     - parameter location: (query) City/state, ZIP, address or neighborhood 
     - parameter page: (query)  (optional, default to 1)
     - parameter sort: (query) relevant|newest|price_high_to_low|price_low_to_high|square_feet|lot_size|price_per_sqft|beds|baths (optional)
     - parameter priceMin: (query)  (optional)
     - parameter priceMax: (query)  (optional)
     - parameter bedsMin: (query)  (optional)
     - parameter bathsMin: (query)  (optional)
     - parameter homeType: (query) house|condo|townhouse|multi_family|land|mobile|coop|other (optional)
     - parameter sqftMin: (query)  (optional)
     - parameter sqftMax: (query)  (optional)
     - parameter lotMin: (query)  (optional)
     - parameter lotMax: (query)  (optional)
     - parameter yearBuiltMin: (query)  (optional)
     - parameter yearBuiltMax: (query)  (optional)
     - parameter maxDaysOnMarket: (query)  (optional)
     - parameter north: (query) Map bounds for tiling past the cap (optional)
     - parameter south: (query)  (optional)
     - parameter east: (query)  (optional)
     - parameter west: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func redfinSearchProperties(location: String, page: Int? = nil, sort: String? = nil, priceMin: Int? = nil, priceMax: Int? = nil, bedsMin: Int? = nil, bathsMin: Double? = nil, homeType: String? = nil, sqftMin: Int? = nil, sqftMax: Int? = nil, lotMin: Int? = nil, lotMax: Int? = nil, yearBuiltMin: Int? = nil, yearBuiltMax: Int? = nil, maxDaysOnMarket: Int? = nil, north: Double? = nil, south: Double? = nil, east: Double? = nil, west: Double? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return redfinSearchPropertiesWithRequestBuilder(location: location, page: page, sort: sort, priceMin: priceMin, priceMax: priceMax, bedsMin: bedsMin, bathsMin: bathsMin, homeType: homeType, sqftMin: sqftMin, sqftMax: sqftMax, lotMin: lotMin, lotMax: lotMax, yearBuiltMin: yearBuiltMin, yearBuiltMax: yearBuiltMax, maxDaysOnMarket: maxDaysOnMarket, north: north, south: south, east: east, west: west).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search properties
     - GET /v1/redfin/search
     - Search Redfin for for-sale / for-rent / recently-sold properties.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter location: (query) City/state, ZIP, address or neighborhood 
     - parameter page: (query)  (optional, default to 1)
     - parameter sort: (query) relevant|newest|price_high_to_low|price_low_to_high|square_feet|lot_size|price_per_sqft|beds|baths (optional)
     - parameter priceMin: (query)  (optional)
     - parameter priceMax: (query)  (optional)
     - parameter bedsMin: (query)  (optional)
     - parameter bathsMin: (query)  (optional)
     - parameter homeType: (query) house|condo|townhouse|multi_family|land|mobile|coop|other (optional)
     - parameter sqftMin: (query)  (optional)
     - parameter sqftMax: (query)  (optional)
     - parameter lotMin: (query)  (optional)
     - parameter lotMax: (query)  (optional)
     - parameter yearBuiltMin: (query)  (optional)
     - parameter yearBuiltMax: (query)  (optional)
     - parameter maxDaysOnMarket: (query)  (optional)
     - parameter north: (query) Map bounds for tiling past the cap (optional)
     - parameter south: (query)  (optional)
     - parameter east: (query)  (optional)
     - parameter west: (query)  (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func redfinSearchPropertiesWithRequestBuilder(location: String, page: Int? = nil, sort: String? = nil, priceMin: Int? = nil, priceMax: Int? = nil, bedsMin: Int? = nil, bathsMin: Double? = nil, homeType: String? = nil, sqftMin: Int? = nil, sqftMax: Int? = nil, lotMin: Int? = nil, lotMax: Int? = nil, yearBuiltMin: Int? = nil, yearBuiltMax: Int? = nil, maxDaysOnMarket: Int? = nil, north: Double? = nil, south: Double? = nil, east: Double? = nil, west: Double? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/redfin/search"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "location": (wrappedValue: location.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
            "price_min": (wrappedValue: priceMin?.encodeToJSON(), isExplode: true),
            "price_max": (wrappedValue: priceMax?.encodeToJSON(), isExplode: true),
            "beds_min": (wrappedValue: bedsMin?.encodeToJSON(), isExplode: true),
            "baths_min": (wrappedValue: bathsMin?.encodeToJSON(), isExplode: true),
            "home_type": (wrappedValue: homeType?.encodeToJSON(), isExplode: true),
            "sqft_min": (wrappedValue: sqftMin?.encodeToJSON(), isExplode: true),
            "sqft_max": (wrappedValue: sqftMax?.encodeToJSON(), isExplode: true),
            "lot_min": (wrappedValue: lotMin?.encodeToJSON(), isExplode: true),
            "lot_max": (wrappedValue: lotMax?.encodeToJSON(), isExplode: true),
            "year_built_min": (wrappedValue: yearBuiltMin?.encodeToJSON(), isExplode: true),
            "year_built_max": (wrappedValue: yearBuiltMax?.encodeToJSON(), isExplode: true),
            "max_days_on_market": (wrappedValue: maxDaysOnMarket?.encodeToJSON(), isExplode: true),
            "north": (wrappedValue: north?.encodeToJSON(), isExplode: true),
            "south": (wrappedValue: south?.encodeToJSON(), isExplode: true),
            "east": (wrappedValue: east?.encodeToJSON(), isExplode: true),
            "west": (wrappedValue: west?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
