//
// TikTokAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class TikTokAPI {

    /**
     General search
     
     - parameter query: (query) Search keyword 
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 20)
     - parameter cursor: (query) Composite pagination cursor (offset.search_id) from a prior page&#39;s pagination.cursor (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokGeneralSearch(query: String, region: String? = nil, count: Int? = nil, cursor: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGeneralSearchWithRequestBuilder(query: query, region: region, count: count, cursor: cursor).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     General search
     - GET /v1/tiktok/search
     - General TikTok search — video results from the Top feed.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Search keyword 
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 20)
     - parameter cursor: (query) Composite pagination cursor (offset.search_id) from a prior page&#39;s pagination.cursor (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokGeneralSearchWithRequestBuilder(query: String, region: String? = nil, count: Int? = nil, cursor: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/tiktok/search"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get comment replies
     
     - parameter commentId: (path)  
     - parameter videoId: (query) Parent video id 
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 20)
     - parameter cursor: (query) Pagination cursor from a prior page&#39;s pagination.cursor (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokGetCommentReplies(commentId: String, videoId: String, region: String? = nil, count: Int? = nil, cursor: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetCommentRepliesWithRequestBuilder(commentId: commentId, videoId: videoId, region: region, count: count, cursor: cursor).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get comment replies
     - GET /v1/tiktok/comments/{comment_id}/replies
     - Get replies to a TikTok comment (best-effort).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter commentId: (path)  
     - parameter videoId: (query) Parent video id 
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 20)
     - parameter cursor: (query) Pagination cursor from a prior page&#39;s pagination.cursor (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokGetCommentRepliesWithRequestBuilder(commentId: String, videoId: String, region: String? = nil, count: Int? = nil, cursor: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/tiktok/comments/{comment_id}/replies"
        let commentIdPreEscape = "\(APIHelper.mapValueToPathItem(commentId))"
        let commentIdPostEscape = commentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{comment_id}", with: commentIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "video_id": (wrappedValue: videoId.encodeToJSON(), isExplode: true),
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get comments
     
     - parameter videoId: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 20)
     - parameter cursor: (query) Pagination cursor from a prior page&#39;s pagination.cursor (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokGetComments(videoId: String, region: String? = nil, count: Int? = nil, cursor: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetCommentsWithRequestBuilder(videoId: videoId, region: region, count: count, cursor: cursor).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get comments
     - GET /v1/tiktok/videos/{video_id}/comments
     - Get top-level comments on a TikTok video.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter videoId: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 20)
     - parameter cursor: (query) Pagination cursor from a prior page&#39;s pagination.cursor (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokGetCommentsWithRequestBuilder(videoId: String, region: String? = nil, count: Int? = nil, cursor: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/tiktok/videos/{video_id}/comments"
        let videoIdPreEscape = "\(APIHelper.mapValueToPathItem(videoId))"
        let videoIdPostEscape = videoIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{video_id}", with: videoIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get followers (deprecated)
     
     - parameter username: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 30)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    @discardableResult
    open class func tiktokGetFollowersDeprecated(username: String, region: String? = nil, count: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetFollowersDeprecatedWithRequestBuilder(username: username, region: region, count: count).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get followers (deprecated)
     - GET /v1/tiktok/users/{username}/followers
     - DEPRECATED — TikTok followers require an authenticated account session. Returns HTTP 410.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter username: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 30)
     - returns: RequestBuilder<AnyCodable> 
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    open class func tiktokGetFollowersDeprecatedWithRequestBuilder(username: String, region: String? = nil, count: Int? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/tiktok/users/{username}/followers"
        let usernamePreEscape = "\(APIHelper.mapValueToPathItem(username))"
        let usernamePostEscape = usernamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{username}", with: usernamePostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get following (deprecated)
     
     - parameter username: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 30)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    @discardableResult
    open class func tiktokGetFollowingDeprecated(username: String, region: String? = nil, count: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetFollowingDeprecatedWithRequestBuilder(username: username, region: region, count: count).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get following (deprecated)
     - GET /v1/tiktok/users/{username}/following
     - DEPRECATED — TikTok following requires an authenticated account session. Returns HTTP 410.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter username: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 30)
     - returns: RequestBuilder<AnyCodable> 
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    open class func tiktokGetFollowingDeprecatedWithRequestBuilder(username: String, region: String? = nil, count: Int? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/tiktok/users/{username}/following"
        let usernamePreEscape = "\(APIHelper.mapValueToPathItem(username))"
        let usernamePostEscape = usernamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{username}", with: usernamePostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get hashtag detail
     
     - parameter name: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokGetHashtagDetail(name: String, region: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetHashtagDetailWithRequestBuilder(name: name, region: region).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get hashtag detail
     - GET /v1/tiktok/hashtags/{name}
     - Get TikTok hashtag/challenge detail.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter name: (path)  
     - parameter region: (query)  (optional, default to "US")
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokGetHashtagDetailWithRequestBuilder(name: String, region: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/tiktok/hashtags/{name}"
        let namePreEscape = "\(APIHelper.mapValueToPathItem(name))"
        let namePostEscape = namePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{name}", with: namePostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get hashtag videos
     
     - parameter name: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 30)
     - parameter cursor: (query) Pagination cursor from a prior page&#39;s pagination.cursor (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokGetHashtagVideos(name: String, region: String? = nil, count: Int? = nil, cursor: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetHashtagVideosWithRequestBuilder(name: name, region: region, count: count, cursor: cursor).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get hashtag videos
     - GET /v1/tiktok/hashtags/{name}/videos
     - Get videos tagged with a TikTok hashtag.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter name: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 30)
     - parameter cursor: (query) Pagination cursor from a prior page&#39;s pagination.cursor (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokGetHashtagVideosWithRequestBuilder(name: String, region: String? = nil, count: Int? = nil, cursor: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/tiktok/hashtags/{name}/videos"
        let namePreEscape = "\(APIHelper.mapValueToPathItem(name))"
        let namePostEscape = namePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{name}", with: namePostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get liked videos (deprecated)
     
     - parameter username: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 30)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    @discardableResult
    open class func tiktokGetLikedVideosDeprecated(username: String, region: String? = nil, count: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetLikedVideosDeprecatedWithRequestBuilder(username: username, region: region, count: count).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get liked videos (deprecated)
     - GET /v1/tiktok/users/{username}/liked
     - DEPRECATED — TikTok liked videos require an authenticated account session. Returns HTTP 410.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter username: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 30)
     - returns: RequestBuilder<AnyCodable> 
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    open class func tiktokGetLikedVideosDeprecatedWithRequestBuilder(username: String, region: String? = nil, count: Int? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/tiktok/users/{username}/liked"
        let usernamePreEscape = "\(APIHelper.mapValueToPathItem(username))"
        let usernamePostEscape = usernamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{username}", with: usernamePostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get music/sound detail
     
     - parameter musicId: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokGetMusicSoundDetail(musicId: String, region: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetMusicSoundDetailWithRequestBuilder(musicId: musicId, region: region).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get music/sound detail
     - GET /v1/tiktok/music/{music_id}
     - Get TikTok sound/music detail.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter musicId: (path)  
     - parameter region: (query)  (optional, default to "US")
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokGetMusicSoundDetailWithRequestBuilder(musicId: String, region: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/tiktok/music/{music_id}"
        let musicIdPreEscape = "\(APIHelper.mapValueToPathItem(musicId))"
        let musicIdPostEscape = musicIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{music_id}", with: musicIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get music videos
     
     - parameter musicId: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 30)
     - parameter cursor: (query) Pagination cursor from a prior page&#39;s pagination.cursor (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokGetMusicVideos(musicId: String, region: String? = nil, count: Int? = nil, cursor: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetMusicVideosWithRequestBuilder(musicId: musicId, region: region, count: count, cursor: cursor).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get music videos
     - GET /v1/tiktok/music/{music_id}/videos
     - Get videos using a given TikTok sound.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter musicId: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 30)
     - parameter cursor: (query) Pagination cursor from a prior page&#39;s pagination.cursor (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokGetMusicVideosWithRequestBuilder(musicId: String, region: String? = nil, count: Int? = nil, cursor: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/tiktok/music/{music_id}/videos"
        let musicIdPreEscape = "\(APIHelper.mapValueToPathItem(musicId))"
        let musicIdPostEscape = musicIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{music_id}", with: musicIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get oEmbed metadata
     
     - parameter url: (query) Full TikTok video or profile URL 
     - parameter region: (query)  (optional, default to "US")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokGetOembedMetadata(url: String, region: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetOembedMetadataWithRequestBuilder(url: url, region: region).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get oEmbed metadata
     - GET /v1/tiktok/oembed
     - Get cheap unauthenticated oEmbed metadata for a TikTok URL.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter url: (query) Full TikTok video or profile URL 
     - parameter region: (query)  (optional, default to "US")
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokGetOembedMetadataWithRequestBuilder(url: String, region: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/tiktok/oembed"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "url": (wrappedValue: url.encodeToJSON(), isExplode: true),
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get related videos
     
     - parameter videoId: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 16)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokGetRelatedVideos(videoId: String, region: String? = nil, count: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetRelatedVideosWithRequestBuilder(videoId: videoId, region: region, count: count).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get related videos
     - GET /v1/tiktok/videos/{video_id}/related
     - Get TikTok's related videos for a given video.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter videoId: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 16)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokGetRelatedVideosWithRequestBuilder(videoId: String, region: String? = nil, count: Int? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/tiktok/videos/{video_id}/related"
        let videoIdPreEscape = "\(APIHelper.mapValueToPathItem(videoId))"
        let videoIdPostEscape = videoIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{video_id}", with: videoIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get reposts
     
     - parameter username: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 30)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokGetReposts(username: String, region: String? = nil, count: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetRepostsWithRequestBuilder(username: username, region: region, count: count).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get reposts
     - GET /v1/tiktok/users/{username}/reposts
     - Get videos a TikTok user has reposted.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter username: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 30)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokGetRepostsWithRequestBuilder(username: String, region: String? = nil, count: Int? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/tiktok/users/{username}/reposts"
        let usernamePreEscape = "\(APIHelper.mapValueToPathItem(username))"
        let usernamePostEscape = usernamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{username}", with: usernamePostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get transcript
     
     - parameter videoId: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokGetTranscript(videoId: String, region: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetTranscriptWithRequestBuilder(videoId: videoId, region: region).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get transcript
     - GET /v1/tiktok/videos/{video_id}/transcript
     - Get subtitle/caption tracks for a TikTok video.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter videoId: (path)  
     - parameter region: (query)  (optional, default to "US")
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokGetTranscriptWithRequestBuilder(videoId: String, region: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/tiktok/videos/{video_id}/transcript"
        let videoIdPreEscape = "\(APIHelper.mapValueToPathItem(videoId))"
        let videoIdPostEscape = videoIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{video_id}", with: videoIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get user profile
     
     - parameter username: (path)  
     - parameter region: (query) Content region (ISO 3166-1 alpha-2) (optional, default to "US")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokGetUserProfile(username: String, region: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetUserProfileWithRequestBuilder(username: username, region: region).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get user profile
     - GET /v1/tiktok/users/{username}
     - Get a TikTok user's full profile.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter username: (path)  
     - parameter region: (query) Content region (ISO 3166-1 alpha-2) (optional, default to "US")
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokGetUserProfileWithRequestBuilder(username: String, region: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/tiktok/users/{username}"
        let usernamePreEscape = "\(APIHelper.mapValueToPathItem(username))"
        let usernamePostEscape = usernamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{username}", with: usernamePostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get user videos
     
     - parameter username: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 30)
     - parameter cursor: (query) Pagination cursor from a prior page&#39;s &#x60;pagination.cursor&#x60; (signer path only). (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokGetUserVideos(username: String, region: String? = nil, count: Int? = nil, cursor: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetUserVideosWithRequestBuilder(username: username, region: region, count: count, cursor: cursor).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get user videos
     - GET /v1/tiktok/users/{username}/videos
     - Get a TikTok user's posted videos.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter username: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 30)
     - parameter cursor: (query) Pagination cursor from a prior page&#39;s &#x60;pagination.cursor&#x60; (signer path only). (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokGetUserVideosWithRequestBuilder(username: String, region: String? = nil, count: Int? = nil, cursor: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/tiktok/users/{username}/videos"
        let usernamePreEscape = "\(APIHelper.mapValueToPathItem(username))"
        let usernamePostEscape = usernamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{username}", with: usernamePostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get video detail
     
     - parameter videoId: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter username: (query) Author handle (skips oEmbed lookup) (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokGetVideoDetail(videoId: String, region: String? = nil, username: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokGetVideoDetailWithRequestBuilder(videoId: videoId, region: region, username: username).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get video detail
     - GET /v1/tiktok/videos/{video_id}
     - Get full metadata for a single TikTok video/post.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter videoId: (path)  
     - parameter region: (query)  (optional, default to "US")
     - parameter username: (query) Author handle (skips oEmbed lookup) (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokGetVideoDetailWithRequestBuilder(videoId: String, region: String? = nil, username: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/tiktok/videos/{video_id}"
        let videoIdPreEscape = "\(APIHelper.mapValueToPathItem(videoId))"
        let videoIdPostEscape = videoIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{video_id}", with: videoIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "username": (wrappedValue: username?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokHealthCheck(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokHealthCheckWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Health check
     - GET /v1/tiktok/health
     - Check health of the TikTok scraper service.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokHealthCheckWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/tiktok/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokHealthCheckHead(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokHealthCheckHeadWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Health check
     - HEAD /v1/tiktok/health
     - Check health of the TikTok scraper service.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokHealthCheckHeadWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/tiktok/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List regions
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokListRegions(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokListRegionsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List regions
     - GET /v1/tiktok/regions
     - List supported TikTok content regions.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokListRegionsWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/tiktok/regions"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search hashtags
     
     - parameter query: (query) Search keyword 
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 20)
     - parameter cursor: (query) Composite pagination cursor (offset.search_id) from a prior page&#39;s pagination.cursor (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokSearchHashtags(query: String, region: String? = nil, count: Int? = nil, cursor: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokSearchHashtagsWithRequestBuilder(query: query, region: region, count: count, cursor: cursor).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search hashtags
     - GET /v1/tiktok/search/hashtags
     - Search TikTok hashtags by keyword.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Search keyword 
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 20)
     - parameter cursor: (query) Composite pagination cursor (offset.search_id) from a prior page&#39;s pagination.cursor (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokSearchHashtagsWithRequestBuilder(query: String, region: String? = nil, count: Int? = nil, cursor: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/tiktok/search/hashtags"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search the TikTok Ad Library
     
     - parameter query: (query) Keyword (ignored when advertiser_id is set) (optional, default to "")
     - parameter advertiserId: (query) Advertiser business id(s) for advertiser search (optional, default to "")
     - parameter region: (query) EU region code (the Ad Library is EU-only) (optional, default to "DE")
     - parameter days: (query)  (optional, default to 30)
     - parameter sort: (query)  (optional, default to "last_shown_date,desc")
     - parameter offset: (query)  (optional, default to 0)
     - parameter searchId: (query)  (optional, default to "")
     - parameter count: (query)  (optional, default to 20)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokSearchTheTiktokAdLibrary(query: String? = nil, advertiserId: String? = nil, region: String? = nil, days: Int? = nil, sort: String? = nil, offset: Int? = nil, searchId: String? = nil, count: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokSearchTheTiktokAdLibraryWithRequestBuilder(query: query, advertiserId: advertiserId, region: region, days: days, sort: sort, offset: offset, searchId: searchId, count: count).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search the TikTok Ad Library
     - GET /v1/tiktok/ads/search
     - Search TikTok's Commercial Content Library (ad transparency) by keyword or advertiser.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Keyword (ignored when advertiser_id is set) (optional, default to "")
     - parameter advertiserId: (query) Advertiser business id(s) for advertiser search (optional, default to "")
     - parameter region: (query) EU region code (the Ad Library is EU-only) (optional, default to "DE")
     - parameter days: (query)  (optional, default to 30)
     - parameter sort: (query)  (optional, default to "last_shown_date,desc")
     - parameter offset: (query)  (optional, default to 0)
     - parameter searchId: (query)  (optional, default to "")
     - parameter count: (query)  (optional, default to 20)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokSearchTheTiktokAdLibraryWithRequestBuilder(query: String? = nil, advertiserId: String? = nil, region: String? = nil, days: Int? = nil, sort: String? = nil, offset: Int? = nil, searchId: String? = nil, count: Int? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/tiktok/ads/search"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query?.encodeToJSON(), isExplode: true),
            "advertiser_id": (wrappedValue: advertiserId?.encodeToJSON(), isExplode: true),
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "days": (wrappedValue: days?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset?.encodeToJSON(), isExplode: true),
            "search_id": (wrappedValue: searchId?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search users
     
     - parameter query: (query) Search keyword 
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 20)
     - parameter cursor: (query) Composite pagination cursor (offset.search_id) from a prior page&#39;s pagination.cursor (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokSearchUsers(query: String, region: String? = nil, count: Int? = nil, cursor: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokSearchUsersWithRequestBuilder(query: query, region: region, count: count, cursor: cursor).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search users
     - GET /v1/tiktok/search/users
     - Search TikTok users by keyword.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Search keyword 
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 20)
     - parameter cursor: (query) Composite pagination cursor (offset.search_id) from a prior page&#39;s pagination.cursor (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokSearchUsersWithRequestBuilder(query: String, region: String? = nil, count: Int? = nil, cursor: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/tiktok/search/users"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search videos
     
     - parameter query: (query) Search keyword 
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 20)
     - parameter cursor: (query) Composite pagination cursor (offset.search_id) from a prior page&#39;s pagination.cursor (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokSearchVideos(query: String, region: String? = nil, count: Int? = nil, cursor: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokSearchVideosWithRequestBuilder(query: query, region: region, count: count, cursor: cursor).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search videos
     - GET /v1/tiktok/search/videos
     - Search TikTok videos by keyword.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Search keyword 
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 20)
     - parameter cursor: (query) Composite pagination cursor (offset.search_id) from a prior page&#39;s pagination.cursor (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokSearchVideosWithRequestBuilder(query: String, region: String? = nil, count: Int? = nil, cursor: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/tiktok/search/videos"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Trending hashtags
     
     - parameter region: (query)  (optional, default to "US")
     - parameter period: (query)  (optional, default to 7)
     - parameter count: (query)  (optional, default to 20)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokTrendingHashtags(region: String? = nil, period: Int? = nil, count: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokTrendingHashtagsWithRequestBuilder(region: region, period: period, count: count).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Trending hashtags
     - GET /v1/tiktok/trending/hashtags
     - Get trending hashtags (mobile Discover surface — view_count + creators).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter region: (query)  (optional, default to "US")
     - parameter period: (query)  (optional, default to 7)
     - parameter count: (query)  (optional, default to 20)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokTrendingHashtagsWithRequestBuilder(region: String? = nil, period: Int? = nil, count: Int? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/tiktok/trending/hashtags"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "period": (wrappedValue: period?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Trending songs
     
     - parameter region: (query)  (optional, default to "US")
     - parameter period: (query)  (optional, default to 7)
     - parameter count: (query)  (optional, default to 20)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokTrendingSongs(region: String? = nil, period: Int? = nil, count: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokTrendingSongsWithRequestBuilder(region: region, period: period, count: count).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Trending songs
     - GET /v1/tiktok/trending/songs
     - Get trending songs/sounds (mobile hot-music feed — ranked by usage).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter region: (query)  (optional, default to "US")
     - parameter period: (query)  (optional, default to 7)
     - parameter count: (query)  (optional, default to 20)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokTrendingSongsWithRequestBuilder(region: String? = nil, period: Int? = nil, count: Int? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/tiktok/trending/songs"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "period": (wrappedValue: period?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Trending videos
     
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 20)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func tiktokTrendingVideos(region: String? = nil, count: Int? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return tiktokTrendingVideosWithRequestBuilder(region: region, count: count).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Trending videos
     - GET /v1/tiktok/trending/videos
     - Get trending videos from the TikTok Explore feed.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter region: (query)  (optional, default to "US")
     - parameter count: (query)  (optional, default to 20)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func tiktokTrendingVideosWithRequestBuilder(region: String? = nil, count: Int? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/tiktok/trending/videos"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
