//
// WalmartAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class WalmartAPI {

    /**
     Browse a category
     
     - parameter path: (query) Browse path, e.g. &#39;electronics/3944&#39;, or a &#39;/cp/...&#39; path 
     - parameter page: (query)  (optional, default to 1)
     - parameter minPrice: (query)  (optional)
     - parameter maxPrice: (query)  (optional)
     - parameter facet: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func walmartBrowseACategory(path: String, page: Int? = nil, minPrice: Double? = nil, maxPrice: Double? = nil, facet: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return walmartBrowseACategoryWithRequestBuilder(path: path, page: page, minPrice: minPrice, maxPrice: maxPrice, facet: facet).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Browse a category
     - GET /v1/walmart/category
     - Browse a Walmart category. Same result shape as search.  No `sort`: Walmart's browse pages ignore it. Sort on `/search` instead.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter path: (query) Browse path, e.g. &#39;electronics/3944&#39;, or a &#39;/cp/...&#39; path 
     - parameter page: (query)  (optional, default to 1)
     - parameter minPrice: (query)  (optional)
     - parameter maxPrice: (query)  (optional)
     - parameter facet: (query)  (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func walmartBrowseACategoryWithRequestBuilder(path: String, page: Int? = nil, minPrice: Double? = nil, maxPrice: Double? = nil, facet: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/walmart/category"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "path": (wrappedValue: path.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "min_price": (wrappedValue: minPrice?.encodeToJSON(), isExplode: true),
            "max_price": (wrappedValue: maxPrice?.encodeToJSON(), isExplode: true),
            "facet": (wrappedValue: facet?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Deals, rollbacks and clearance
     
     - parameter page: (query)  (optional, default to 1)
     - parameter minPrice: (query)  (optional)
     - parameter maxPrice: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func walmartDealsRollbacksAndClearance(page: Int? = nil, minPrice: Double? = nil, maxPrice: Double? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return walmartDealsRollbacksAndClearanceWithRequestBuilder(page: page, minPrice: minPrice, maxPrice: maxPrice).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Deals, rollbacks and clearance
     - GET /v1/walmart/deals
     - Walmart's current deals, rollbacks and clearance.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter page: (query)  (optional, default to 1)
     - parameter minPrice: (query)  (optional)
     - parameter maxPrice: (query)  (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func walmartDealsRollbacksAndClearanceWithRequestBuilder(page: Int? = nil, minPrice: Double? = nil, maxPrice: Double? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/walmart/deals"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "min_price": (wrappedValue: minPrice?.encodeToJSON(), isExplode: true),
            "max_price": (wrappedValue: maxPrice?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get a seller's catalogue
     
     - parameter sellerId: (path) Numeric catalog seller id, e.g. &#39;101040442&#39; — the &#x60;catalog_seller_id&#x60; on a product, NOT the 32-char hex &#x60;seller_id&#x60; (which 404s). 
     - parameter query: (query) Required — Walmart returns nothing for a seller facet alone 
     - parameter page: (query)  (optional, default to 1)
     - parameter sort: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func walmartGetASellerSCatalogue(sellerId: String, query: String, page: Int? = nil, sort: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return walmartGetASellerSCatalogueWithRequestBuilder(sellerId: sellerId, query: query, page: page, sort: sort).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get a seller's catalogue
     - GET /v1/walmart/sellers/{seller_id}/products
     - A marketplace seller's catalogue, scoped by a search term.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter sellerId: (path) Numeric catalog seller id, e.g. &#39;101040442&#39; — the &#x60;catalog_seller_id&#x60; on a product, NOT the 32-char hex &#x60;seller_id&#x60; (which 404s). 
     - parameter query: (query) Required — Walmart returns nothing for a seller facet alone 
     - parameter page: (query)  (optional, default to 1)
     - parameter sort: (query)  (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func walmartGetASellerSCatalogueWithRequestBuilder(sellerId: String, query: String, page: Int? = nil, sort: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/walmart/sellers/{seller_id}/products"
        let sellerIdPreEscape = "\(APIHelper.mapValueToPathItem(sellerId))"
        let sellerIdPostEscape = sellerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{seller_id}", with: sellerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get product detail
     
     - parameter itemId: (path) Walmart usItemId, e.g. &#39;5689919121&#39; 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func walmartGetProductDetail(itemId: String, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return walmartGetProductDetailWithRequestBuilder(itemId: itemId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get product detail
     - GET /v1/walmart/products/{item_id}
     - Full product detail — price, stock, specs, variants, seller, reviews sample.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter itemId: (path) Walmart usItemId, e.g. &#39;5689919121&#39; 
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func walmartGetProductDetailWithRequestBuilder(itemId: String) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/walmart/products/{item_id}"
        let itemIdPreEscape = "\(APIHelper.mapValueToPathItem(itemId))"
        let itemIdPostEscape = itemIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{item_id}", with: itemIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get product reviews
     
     - parameter itemId: (path) Walmart usItemId, e.g. &#39;5689919121&#39; 
     - parameter page: (query)  (optional, default to 1)
     - parameter sort: (query) relevancy | submission-desc | submission-asc | rating-desc | rating-asc | helpful (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func walmartGetProductReviews(itemId: String, page: Int? = nil, sort: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return walmartGetProductReviewsWithRequestBuilder(itemId: itemId, page: page, sort: sort).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get product reviews
     - GET /v1/walmart/products/{item_id}/reviews
     - Paginated reviews with the full star histogram. 10 per page.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter itemId: (path) Walmart usItemId, e.g. &#39;5689919121&#39; 
     - parameter page: (query)  (optional, default to 1)
     - parameter sort: (query) relevancy | submission-desc | submission-asc | rating-desc | rating-asc | helpful (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func walmartGetProductReviewsWithRequestBuilder(itemId: String, page: Int? = nil, sort: String? = nil) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/walmart/products/{item_id}/reviews"
        let itemIdPreEscape = "\(APIHelper.mapValueToPathItem(itemId))"
        let itemIdPostEscape = itemIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{item_id}", with: itemIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get seller profile
     
     - parameter sellerId: (path) Numeric catalog seller id, e.g. &#39;101040442&#39; — the &#x60;catalog_seller_id&#x60; on a product, NOT the 32-char hex &#x60;seller_id&#x60; (which 404s). 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func walmartGetSellerProfile(sellerId: String, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return walmartGetSellerProfileWithRequestBuilder(sellerId: sellerId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get seller profile
     - GET /v1/walmart/sellers/{seller_id}
     - Marketplace seller profile — contact details, address, rating, policies.  No `page`: adding one makes Walmart's own SSR throw. Use `/sellers/{id}/products` for the catalogue.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter sellerId: (path) Numeric catalog seller id, e.g. &#39;101040442&#39; — the &#x60;catalog_seller_id&#x60; on a product, NOT the 32-char hex &#x60;seller_id&#x60; (which 404s). 
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func walmartGetSellerProfileWithRequestBuilder(sellerId: String) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/walmart/sellers/{seller_id}"
        let sellerIdPreEscape = "\(APIHelper.mapValueToPathItem(sellerId))"
        let sellerIdPostEscape = sellerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{seller_id}", with: sellerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get store + nearby stores
     
     - parameter storeId: (path) Walmart store number, e.g. &#39;100&#39; 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func walmartGetStoreNearbyStores(storeId: String, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return walmartGetStoreNearbyStoresWithRequestBuilder(storeId: storeId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get store + nearby stores
     - GET /v1/walmart/stores/{store_id}
     - Store detail with hours, per-department services, and nearby stores.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter storeId: (path) Walmart store number, e.g. &#39;100&#39; 
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func walmartGetStoreNearbyStoresWithRequestBuilder(storeId: String) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/walmart/stores/{store_id}"
        let storeIdPreEscape = "\(APIHelper.mapValueToPathItem(storeId))"
        let storeIdPostEscape = storeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{store_id}", with: storeIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List supported markets
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func walmartListSupportedMarkets(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return walmartListSupportedMarketsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List supported markets
     - GET /v1/walmart/markets
     - Supported Walmart markets.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func walmartListSupportedMarketsWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/walmart/markets"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search products
     
     - parameter query: (query) Search keywords, e.g. &#39;laptop&#39; 
     - parameter page: (query) Results dry up after page 10 (optional, default to 1)
     - parameter sort: (query) best_match | best_seller | price_low | price_high | rating_high | new (optional)
     - parameter minPrice: (query)  (optional)
     - parameter maxPrice: (query)  (optional)
     - parameter facet: (query) Facet filter, e.g. &#39;brand:HP&#39; (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func walmartSearchProducts(query: String, page: Int? = nil, sort: String? = nil, minPrice: Double? = nil, maxPrice: Double? = nil, facet: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return walmartSearchProductsWithRequestBuilder(query: query, page: page, sort: sort, minPrice: minPrice, maxPrice: maxPrice, facet: facet).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search products
     - GET /v1/walmart/search
     - Search walmart.com. ~40-60 organic products per page; ad tiles are dropped.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Search keywords, e.g. &#39;laptop&#39; 
     - parameter page: (query) Results dry up after page 10 (optional, default to 1)
     - parameter sort: (query) best_match | best_seller | price_low | price_high | rating_high | new (optional)
     - parameter minPrice: (query)  (optional)
     - parameter maxPrice: (query)  (optional)
     - parameter facet: (query) Facet filter, e.g. &#39;brand:HP&#39; (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func walmartSearchProductsWithRequestBuilder(query: String, page: Int? = nil, sort: String? = nil, minPrice: Double? = nil, maxPrice: Double? = nil, facet: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/walmart/search"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
            "min_price": (wrappedValue: minPrice?.encodeToJSON(), isExplode: true),
            "max_price": (wrappedValue: maxPrice?.encodeToJSON(), isExplode: true),
            "facet": (wrappedValue: facet?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search suggestions
     
     - parameter query: (query) Partial search term, e.g. &#39;lapt&#39; 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func walmartSearchSuggestions(query: String, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return walmartSearchSuggestionsWithRequestBuilder(query: query).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search suggestions
     - GET /v1/walmart/autocomplete
     - Walmart search-box suggestions.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Partial search term, e.g. &#39;lapt&#39; 
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func walmartSearchSuggestionsWithRequestBuilder(query: String) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/walmart/autocomplete"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Walmart scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func walmartWalmartScraperHealthCheck(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return walmartWalmartScraperHealthCheckWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Walmart scraper health check
     - GET /v1/walmart/health
     - Check health of the Walmart scraper service (accepts HEAD for UptimeRobot).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func walmartWalmartScraperHealthCheckWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/walmart/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Walmart scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func walmartWalmartScraperHealthCheckHead(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return walmartWalmartScraperHealthCheckHeadWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Walmart scraper health check
     - HEAD /v1/walmart/health
     - Check health of the Walmart scraper service (accepts HEAD for UptimeRobot).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func walmartWalmartScraperHealthCheckHeadWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/walmart/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
