//
// ZillowAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ZillowAPI {

    /**
     Get agent profile + listings
     
     - parameter username: (query) Zillow profile username (optional)
     - parameter url: (query) Full Zillow /profile/... URL (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func zillowGetAgentProfileListings(username: String? = nil, url: String? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return zillowGetAgentProfileListingsWithRequestBuilder(username: username, url: url).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get agent profile + listings
     - GET /v1/zillow/agent
     - Get a Zillow professional's profile and their active listings.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter username: (query) Zillow profile username (optional)
     - parameter url: (query) Full Zillow /profile/... URL (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func zillowGetAgentProfileListingsWithRequestBuilder(username: String? = nil, url: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/zillow/agent"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "username": (wrappedValue: username?.encodeToJSON(), isExplode: true),
            "url": (wrappedValue: url?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get property detail
     
     - parameter zpid: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func zillowGetPropertyDetail(zpid: String, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return zillowGetPropertyDetailWithRequestBuilder(zpid: zpid).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get property detail
     - GET /v1/zillow/property/{zpid}
     - Get a single Zillow property's full detail by zpid.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter zpid: (path)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func zillowGetPropertyDetailWithRequestBuilder(zpid: String) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/v1/zillow/property/{zpid}"
        let zpidPreEscape = "\(APIHelper.mapValueToPathItem(zpid))"
        let zpidPostEscape = zpidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{zpid}", with: zpidPostEscape, options: .literal, range: nil)
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get property detail by URL
     
     - parameter url: (query) Full Zillow /homedetails/... URL 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func zillowGetPropertyDetailByUrl(url: String, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return zillowGetPropertyDetailByUrlWithRequestBuilder(url: url).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get property detail by URL
     - GET /v1/zillow/property
     - Get a single Zillow property's full detail by its homedetails URL.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter url: (query) Full Zillow /homedetails/... URL 
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func zillowGetPropertyDetailByUrlWithRequestBuilder(url: String) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/zillow/property"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "url": (wrappedValue: url.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List coverage markets
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func zillowListCoverageMarkets(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return zillowListCoverageMarketsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List coverage markets
     - GET /v1/zillow/markets
     - List Zillow coverage regions (US + Canada).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func zillowListCoverageMarketsWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/zillow/markets"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Region/address suggestions
     
     - parameter query: (query) Partial location — city, ZIP, address, neighborhood 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func zillowRegionAddressSuggestions(query: String, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return zillowRegionAddressSuggestionsWithRequestBuilder(query: query).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Region/address suggestions
     - GET /v1/zillow/autocomplete
     - Resolve a search term to Zillow regions/addresses.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter query: (query) Partial location — city, ZIP, address, neighborhood 
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func zillowRegionAddressSuggestionsWithRequestBuilder(query: String) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/zillow/autocomplete"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search properties
     
     - parameter location: (query) City/state, ZIP, address or neighborhood 
     - parameter status: (query) for_sale|for_rent|sold (optional, default to "for_sale")
     - parameter page: (query)  (optional, default to 1)
     - parameter sort: (query) homes_for_you|newest|price_high_to_low|price_low_to_high|bedrooms|bathrooms|square_feet|lot_size|year_built (optional)
     - parameter priceMin: (query)  (optional)
     - parameter priceMax: (query)  (optional)
     - parameter bedsMin: (query)  (optional)
     - parameter bathsMin: (query)  (optional)
     - parameter homeType: (query) houses|condos|townhomes|apartments|manufactured|lots|multi_family (optional)
     - parameter sqftMin: (query)  (optional)
     - parameter sqftMax: (query)  (optional)
     - parameter lotMin: (query)  (optional)
     - parameter lotMax: (query)  (optional)
     - parameter yearBuiltMin: (query)  (optional)
     - parameter yearBuiltMax: (query)  (optional)
     - parameter hoaMax: (query)  (optional)
     - parameter keywords: (query)  (optional)
     - parameter daysOn: (query)  (optional)
     - parameter north: (query) Map bounds for tiling past the 820 cap (optional)
     - parameter south: (query)  (optional)
     - parameter east: (query)  (optional)
     - parameter west: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func zillowSearchProperties(location: String, status: String? = nil, page: Int? = nil, sort: String? = nil, priceMin: Int? = nil, priceMax: Int? = nil, bedsMin: Int? = nil, bathsMin: Double? = nil, homeType: String? = nil, sqftMin: Int? = nil, sqftMax: Int? = nil, lotMin: Int? = nil, lotMax: Int? = nil, yearBuiltMin: Int? = nil, yearBuiltMax: Int? = nil, hoaMax: Int? = nil, keywords: String? = nil, daysOn: String? = nil, north: Double? = nil, south: Double? = nil, east: Double? = nil, west: Double? = nil, apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return zillowSearchPropertiesWithRequestBuilder(location: location, status: status, page: page, sort: sort, priceMin: priceMin, priceMax: priceMax, bedsMin: bedsMin, bathsMin: bathsMin, homeType: homeType, sqftMin: sqftMin, sqftMax: sqftMax, lotMin: lotMin, lotMax: lotMax, yearBuiltMin: yearBuiltMin, yearBuiltMax: yearBuiltMax, hoaMax: hoaMax, keywords: keywords, daysOn: daysOn, north: north, south: south, east: east, west: west).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search properties
     - GET /v1/zillow/search
     - Search Zillow for for-sale / for-rent / recently-sold properties.
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - parameter location: (query) City/state, ZIP, address or neighborhood 
     - parameter status: (query) for_sale|for_rent|sold (optional, default to "for_sale")
     - parameter page: (query)  (optional, default to 1)
     - parameter sort: (query) homes_for_you|newest|price_high_to_low|price_low_to_high|bedrooms|bathrooms|square_feet|lot_size|year_built (optional)
     - parameter priceMin: (query)  (optional)
     - parameter priceMax: (query)  (optional)
     - parameter bedsMin: (query)  (optional)
     - parameter bathsMin: (query)  (optional)
     - parameter homeType: (query) houses|condos|townhomes|apartments|manufactured|lots|multi_family (optional)
     - parameter sqftMin: (query)  (optional)
     - parameter sqftMax: (query)  (optional)
     - parameter lotMin: (query)  (optional)
     - parameter lotMax: (query)  (optional)
     - parameter yearBuiltMin: (query)  (optional)
     - parameter yearBuiltMax: (query)  (optional)
     - parameter hoaMax: (query)  (optional)
     - parameter keywords: (query)  (optional)
     - parameter daysOn: (query)  (optional)
     - parameter north: (query) Map bounds for tiling past the 820 cap (optional)
     - parameter south: (query)  (optional)
     - parameter east: (query)  (optional)
     - parameter west: (query)  (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func zillowSearchPropertiesWithRequestBuilder(location: String, status: String? = nil, page: Int? = nil, sort: String? = nil, priceMin: Int? = nil, priceMax: Int? = nil, bedsMin: Int? = nil, bathsMin: Double? = nil, homeType: String? = nil, sqftMin: Int? = nil, sqftMax: Int? = nil, lotMin: Int? = nil, lotMax: Int? = nil, yearBuiltMin: Int? = nil, yearBuiltMax: Int? = nil, hoaMax: Int? = nil, keywords: String? = nil, daysOn: String? = nil, north: Double? = nil, south: Double? = nil, east: Double? = nil, west: Double? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/zillow/search"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "location": (wrappedValue: location.encodeToJSON(), isExplode: true),
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
            "price_min": (wrappedValue: priceMin?.encodeToJSON(), isExplode: true),
            "price_max": (wrappedValue: priceMax?.encodeToJSON(), isExplode: true),
            "beds_min": (wrappedValue: bedsMin?.encodeToJSON(), isExplode: true),
            "baths_min": (wrappedValue: bathsMin?.encodeToJSON(), isExplode: true),
            "home_type": (wrappedValue: homeType?.encodeToJSON(), isExplode: true),
            "sqft_min": (wrappedValue: sqftMin?.encodeToJSON(), isExplode: true),
            "sqft_max": (wrappedValue: sqftMax?.encodeToJSON(), isExplode: true),
            "lot_min": (wrappedValue: lotMin?.encodeToJSON(), isExplode: true),
            "lot_max": (wrappedValue: lotMax?.encodeToJSON(), isExplode: true),
            "year_built_min": (wrappedValue: yearBuiltMin?.encodeToJSON(), isExplode: true),
            "year_built_max": (wrappedValue: yearBuiltMax?.encodeToJSON(), isExplode: true),
            "hoa_max": (wrappedValue: hoaMax?.encodeToJSON(), isExplode: true),
            "keywords": (wrappedValue: keywords?.encodeToJSON(), isExplode: true),
            "days_on": (wrappedValue: daysOn?.encodeToJSON(), isExplode: true),
            "north": (wrappedValue: north?.encodeToJSON(), isExplode: true),
            "south": (wrappedValue: south?.encodeToJSON(), isExplode: true),
            "east": (wrappedValue: east?.encodeToJSON(), isExplode: true),
            "west": (wrappedValue: west?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Zillow scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func zillowZillowScraperHealthCheck(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return zillowZillowScraperHealthCheckWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Zillow scraper health check
     - GET /v1/zillow/health
     - Check health of the Zillow scraper service (accepts HEAD for UptimeRobot).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func zillowZillowScraperHealthCheckWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/zillow/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Zillow scraper health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func zillowZillowScraperHealthCheckHead(apiResponseQueue: DispatchQueue = ScrapeBadgerAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return zillowZillowScraperHealthCheckHeadWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Zillow scraper health check
     - HEAD /v1/zillow/health
     - Check health of the Zillow scraper service (accepts HEAD for UptimeRobot).
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func zillowZillowScraperHealthCheckHeadWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v1/zillow/health"
        let localVariableURLString = ScrapeBadgerAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = ScrapeBadgerAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "HEAD", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
